export const AboutTextsEng = [
  {
    title: "",
    text: `The Executed Renaissance (or "Red Renaissance", Ukrainian: Розстріляне відродження, Червоний ренесанс, romanized: Rozstriliane vidrodzhennia, Chervonyi renesans) is a term used to describe the generation of Ukrainian language poets, writers, and artists of the 1920s and early 1930s who lived in the Ukrainian Socialist Soviet Republic.\n\nFollowing the 1917 Bolshevik Revolution, Lenin's nationality policies of Korenizatsiya (lit. "Indigenization") favored the revival of minority and heritage languages, encouraging them to be taught in the schools and published and providing them with material support and visibility. The poets and writers of the Ukrainianization generation were often resident in the Slovo Building in Kharkiv, which was then the capital of Soviet Ukraine. With the 1929's Great Turn or "Great Break", newly appointed Soviet Premier and CPSU Secretary General Joseph Stalin reversed those policies in favor of State centralisation, Socialist Realism, and Russification. While outwardly pro-Soviet, Ukrainian language school teachers, poets, and writers refused to submit to Stalin's restoration of Tsarist policies of linguistic imperialism. In retaliation, Ukrainian language schoolteachers, as well as poets, writers and dramatists who wrote in the same language were arrested en masse, deported to the Gulag, imprisoned or executed. Those victims were also part of Stalin's larger 1937-1938 Great Purge, with its most infamous killing field being at Sandarmokh forest, a mass grave site in Karelia where an estimated 6000 political prisoners from the Solovki concentration camp were secretly executed and buried by the NKVD.\n\n"The Executed Renaissance", as a term, was first suggested in 1959 in Paris by anti-communist Polish émigré publisher Jerzy Giedroyc of the influential Kultura magazine. He was writing to Ukrainian émigré and literary critic Yuriy Lavrinenko to recommend the title for the 1959 anthology of the best Ukrainian literature by the Ukrainianization generation.\n\nIn a 2023 article for The Guardian, Joseph Stalin's destruction of the Executed Renaissance was compared to a second alleged decimation of Ukrainian intellectuals by the Russian military during Vladimir Putin's invasion of Ukraine, with alleged killings on the battlefronts, trenches as well as in strikes on civilian areas.\n\n`,
  },
  {
    title: "Background",
    text: `The collapse of the Russian Empire during the First World War, the abolition of imperial censorship, the establishment of an independent Ukrainian State, and the cultural leniency of the Soviet regime in the 1920s together led to an astonishing renaissance of literary and cultural activities in Ukraine. Scores of new writers and poets appeared and formed dozens of literary groups that changed the face of Ukrainian literature. These processes were supported by the policies of nativization (in Ukraine it was called Ukrainization), the New Economic Policy of State Capitalism (1921–1927), and the drive to eliminate illiteracy.`,
  },
  {
    title: "A new elite",
    text: `Lavrinenko, however, saw "the Executed Renaissance" as more than just the title of an anthology. He promoted it as a term encapsulating the martyrdom of Ukrainian poets and their legacy and power to resurrect Ukrainian culture. The Executed Renaissance paradigm, together with the national-communist perspective and as a framework for the nationalization of Ukraine's early Soviet intellectuals, would later emerge as part of an effort to establish a national opposition to the Communist regime with the new intellectual elite eventually contributing to a struggle for an independent and united country.\n\nThe main elements in the outlook of the new Ukrainian intellectuals were rebellion, independent thought, and genuine belief in their own ideals. The intellectuals emphasised the individual rather than the masses. Like many other proponents of inner emigration in a police state, their outward "Sovietness" concealed deep searches and queries.\n\nArising from the lower classes (servants, families of priests, industrial workers and peasants), the new generation of the Ukrainian elite often lacked the opportunity for systematic education because of war, famine and the need to earn their daily bread. Working "on the brink of the possible", using every opportunity to get in contact with world culture and to spread the wings of their creativity, the new generation of the Ukrainian artistic elite were imbued with the latest trends and created truly topical art.\n\nAt this time a new generation arose, bearing the moral burden of victories and defeats in the struggle for national independence, with an understanding of Ukraine's path in world history, independent in its judgements, with diverse ideas about the development of Ukrainian literature, when, according to Solomiia Pavlychko, literature\n\n“got a much wider audience than ever before. The level of education of this audience has increased. For the first time, a large number of writers and intellectuals worked in literature. For the first time Ukrainian scientists spoke to the audience of national universities. For the first time different artistic directions, groups, and schools were rapidly differentiated. However, the tendency for the modernization of cultural life coexisted from the outset with a parallel tendency for its subordination to ideology and then to complete destruction."\n\n`,
  },
  {
    title: "Innovation",
    text: `The writers of the Ukrainian (Red) Renaissance divided prose in two: plot (narrative) prose and non-plot prose. In the non-plot works, it was not the sentence or the word that was paramount, but the subtext, the spirit, or as Khvylovyi put it, the "smell of the word". The style of strong feelings and penetration of phenomena is called "neo-romanticism" or "expressionism". Among the many Ukrainian-language authors working in this style were Mykola Khvylovy ("Julia Shpol"), Yurii Yanovsky, Andrii Holovko, Oleksa Vlyko, Les Kurbas and Mykola Kulish.\n\nThe main themes of Khvylovy's novel Ya (Romantyka) (I am (romance)) are disappointment in the Revolution, and the screaming contradictions and divided nature of human beings at that time. The main character is without a name, and therefore without personality or soul. For the sake of the Revolution he murders his mother and then reproves himself: "Was the Revolution worth such a sacrifice?"\n\nIn Valeryan Pidmogylny's novel The City, for the first time in Ukrainian literature, elements of existentialism emerged. In pursuit of pleasure its protagonist advances from the satisfaction of his physical desires to the highest religious needs. Even with such a complex subject matter, however, the author does not turn his novel into a simple narrative of "people's" philosophy, but grasps it creatively in its application to a national worldview.\n\nIn the Ukrainian-language poetry of the time, the most interesting development is the quest pursued by the Symbolists Olexandr Oles and Pavlo Tychyna. In The Clarinets of the Sun, Tychyna reflected the breadth of an educated and subtle mind contemplating the richness of his national heritage and striving to uncover its root causes.\n\nWhen the Communist Party of the USSR realized it could not control such writers[clarification needed], it began to use impermissible methods of repression: it forced them into silence, subjected them to crushing public criticism, and arrested or executed them. Writers faced a choice between suicide (Khvylovyi in 1933) and the concentration camps (Gulag) (B. Antonenko-Davidovich and Ostap Vyshnya); they could retreat into silence (Ivan Bahrianyi and V. Domontovich), leave Ukraine (V. Vynnychenko and Yevhen Malaniuk), or write works that glorified the Communist Party (P. Tychyna and Mykola Bazhan). Most artists of this brief Renaissance were arrested and imprisoned or shot.\n\n`,
  },
  {
    title: "Deportation, arrests, executions (1933–1938)",
    text: `In 1927, Stalin abolished the New Economic Policy and turned to the forced industrialisation and the collectivization of agriculture of the First Five-Year Plan.\n\nChanges in cultural politics also occurred. An early example was the 1930 show trial of the "Union for the Freedom of Ukraine" at which 45 intellectuals, higher education professors, writers, a theologian and a priest were publicly prosecuted in Kharkiv, then capital of Soviet Ukraine. Fifteen of the accused were executed, many more with links to the defendants (248) were sent to the camps. (This was one of a series of contemporary show trials, held in the North Caucasus, 1929 in Shakhty, and in Moscow, the 1930 Industrial Party Trial and the 1931 Menshevik Trial.)\n\nThe systematic elimination of the Ukrainian intelligentsia dates back to May 1933 when Mykhailo Yalovyi was arrested; in response Mykola Khvylovy committed suicide in the "Slovo" (Word) Building in Kharkiv. The campaign ran from 1934 to 1940, reaching a peak during the Great Terror of 1937–1938. A total of 223 writers were arrested and in a number of cases imprisoned and shot. Almost three hundred representatives of the Ukrainian Renaissance of the 1920s and 1930s were shot between 27 October and 4 November 1937 at Sandarmokh, a massive killing field in Karelia (northwest Russia).\n\nSome important representatives of this generation survived. Many remained in the Soviet Union: Oleksandr Dovzhenko, Pavlo Tychyna, Maksym Rylskyi, Borys Antonenko-Davydovych, Ostap Vyshnia, and Mykola Bazhan. A few emigrated: Ulas Samchuk, George Shevelov, and Ivan Bahrianyi.\n\nThe scale of the tragedy\nExact figures for Ukrainian intellectuals imprisoned and executed during the Great Terror are not available. It is, by comparison, relatively straightfoward to determine how many writers were involved. The "Slovo" Association (Ukrainian writers in emigration) sent its assessment on 20 December 1954 to the Second All-Union Congress of Writers in the USSR: in 1930, works by 259 Ukrainian writers were in print; after 1938 only 36 writers were published (13.9% of the earlier total). According to "Slovo", 192 of the "missing" 223 writers were deported, sent to the Gulag or executed; a further 16 disappeared; and eight writers committed suicide.\n\nThese data are confirmed by The Altar of Sorrow (ed., Olexii Musiienko), a martyrology of Ukrainian writers, which numbers 246 writer-victims of Stalin's terror. Other sources indicate that 228 of 260 Ukrainian writers were deported, imprisoned or shot.`,
  }
];

export const AboutImagesEng = [
  {
    path: 'krushelnycki.jpeg',
    caption: `The Krushelnytskyi family, the beginning of the 1930s. Sitting (from left to right): Volodymyra, Taras, Maria (mother), Larisa and father Antin. Standing: Ostap, Galya (Ivan's wife), Ivan, Natalya (Bohdan's wife), Bohdan. In 1934-37 Volodymyra, Taras, Antin, Ostap, Ivan and Bohdan were repressed and executed. This photo became a symbol of the extermination of the Ukrainian intelligentsia by the Stalinist regime.`
  }
]

export const AboutTextsUkr = [
  {
    title: "",
    text: `The Executed Renaissance (or "Red Renaissance", Ukrainian: Розстріляне відродження, Червоний ренесанс, romanized: Rozstriliane vidrodzhennia, Chervonyi renesans) is a term used to describe the generation of Ukrainian language poets, writers, and artists of the 1920s and early 1930s who lived in the Ukrainian Socialist Soviet Republic.\n\nFollowing the 1917 Bolshevik Revolution, Lenin's nationality policies of Korenizatsiya (lit. "Indigenization") favored the revival of minority and heritage languages, encouraging them to be taught in the schools and published and providing them with material support and visibility. The poets and writers of the Ukrainianization generation were often resident in the Slovo Building in Kharkiv, which was then the capital of Soviet Ukraine. With the 1929's Great Turn or "Great Break", newly appointed Soviet Premier and CPSU Secretary General Joseph Stalin reversed those policies in favor of State centralisation, Socialist Realism, and Russification. While outwardly pro-Soviet, Ukrainian language school teachers, poets, and writers refused to submit to Stalin's restoration of Tsarist policies of linguistic imperialism. In retaliation, Ukrainian language schoolteachers, as well as poets, writers and dramatists who wrote in the same language were arrested en masse, deported to the Gulag, imprisoned or executed. Those victims were also part of Stalin's larger 1937-1938 Great Purge, with its most infamous killing field being at Sandarmokh forest, a mass grave site in Karelia where an estimated 6000 political prisoners from the Solovki concentration camp were secretly executed and buried by the NKVD.\n\n"The Executed Renaissance", as a term, was first suggested in 1959 in Paris by anti-communist Polish émigré publisher Jerzy Giedroyc of the influential Kultura magazine. He was writing to Ukrainian émigré and literary critic Yuriy Lavrinenko to recommend the title for the 1959 anthology of the best Ukrainian literature by the Ukrainianization generation.\n\nIn a 2023 article for The Guardian, Joseph Stalin's destruction of the Executed Renaissance was compared to a second alleged decimation of Ukrainian intellectuals by the Russian military during Vladimir Putin's invasion of Ukraine, with alleged killings on the battlefronts, trenches as well as in strikes on civilian areas.\n\n`,
  },
  {
    title: "Background",
    text: `The collapse of the Russian Empire during the First World War, the abolition of imperial censorship, the establishment of an independent Ukrainian State, and the cultural leniency of the Soviet regime in the 1920s together led to an astonishing renaissance of literary and cultural activities in Ukraine. Scores of new writers and poets appeared and formed dozens of literary groups that changed the face of Ukrainian literature. These processes were supported by the policies of nativization (in Ukraine it was called Ukrainization), the New Economic Policy of State Capitalism (1921–1927), and the drive to eliminate illiteracy.`,
  },
  {
    title: "A new elite",
    text: `Lavrinenko, however, saw "the Executed Renaissance" as more than just the title of an anthology. He promoted it as a term encapsulating the martyrdom of Ukrainian poets and their legacy and power to resurrect Ukrainian culture. The Executed Renaissance paradigm, together with the national-communist perspective and as a framework for the nationalization of Ukraine's early Soviet intellectuals, would later emerge as part of an effort to establish a national opposition to the Communist regime with the new intellectual elite eventually contributing to a struggle for an independent and united country.\n\nThe main elements in the outlook of the new Ukrainian intellectuals were rebellion, independent thought, and genuine belief in their own ideals. The intellectuals emphasised the individual rather than the masses. Like many other proponents of inner emigration in a police state, their outward "Sovietness" concealed deep searches and queries.\n\nArising from the lower classes (servants, families of priests, industrial workers and peasants), the new generation of the Ukrainian elite often lacked the opportunity for systematic education because of war, famine and the need to earn their daily bread. Working "on the brink of the possible", using every opportunity to get in contact with world culture and to spread the wings of their creativity, the new generation of the Ukrainian artistic elite were imbued with the latest trends and created truly topical art.\n\nAt this time a new generation arose, bearing the moral burden of victories and defeats in the struggle for national independence, with an understanding of Ukraine's path in world history, independent in its judgements, with diverse ideas about the development of Ukrainian literature, when, according to Solomiia Pavlychko, literature\n\n“got a much wider audience than ever before. The level of education of this audience has increased. For the first time, a large number of writers and intellectuals worked in literature. For the first time Ukrainian scientists spoke to the audience of national universities. For the first time different artistic directions, groups, and schools were rapidly differentiated. However, the tendency for the modernization of cultural life coexisted from the outset with a parallel tendency for its subordination to ideology and then to complete destruction."\n\n`,
  },
  {
    title: "Innovation",
    text: `The writers of the Ukrainian (Red) Renaissance divided prose in two: plot (narrative) prose and non-plot prose. In the non-plot works, it was not the sentence or the word that was paramount, but the subtext, the spirit, or as Khvylovyi put it, the "smell of the word". The style of strong feelings and penetration of phenomena is called "neo-romanticism" or "expressionism". Among the many Ukrainian-language authors working in this style were Mykola Khvylovy ("Julia Shpol"), Yurii Yanovsky, Andrii Holovko, Oleksa Vlyko, Les Kurbas and Mykola Kulish.\n\nThe main themes of Khvylovy's novel Ya (Romantyka) (I am (romance)) are disappointment in the Revolution, and the screaming contradictions and divided nature of human beings at that time. The main character is without a name, and therefore without personality or soul. For the sake of the Revolution he murders his mother and then reproves himself: "Was the Revolution worth such a sacrifice?"\n\nIn Valeryan Pidmogylny's novel The City, for the first time in Ukrainian literature, elements of existentialism emerged. In pursuit of pleasure its protagonist advances from the satisfaction of his physical desires to the highest religious needs. Even with such a complex subject matter, however, the author does not turn his novel into a simple narrative of "people's" philosophy, but grasps it creatively in its application to a national worldview.\n\nIn the Ukrainian-language poetry of the time, the most interesting development is the quest pursued by the Symbolists Olexandr Oles and Pavlo Tychyna. In The Clarinets of the Sun, Tychyna reflected the breadth of an educated and subtle mind contemplating the richness of his national heritage and striving to uncover its root causes.\n\nWhen the Communist Party of the USSR realized it could not control such writers[clarification needed], it began to use impermissible methods of repression: it forced them into silence, subjected them to crushing public criticism, and arrested or executed them. Writers faced a choice between suicide (Khvylovyi in 1933) and the concentration camps (Gulag) (B. Antonenko-Davidovich and Ostap Vyshnya); they could retreat into silence (Ivan Bahrianyi and V. Domontovich), leave Ukraine (V. Vynnychenko and Yevhen Malaniuk), or write works that glorified the Communist Party (P. Tychyna and Mykola Bazhan). Most artists of this brief Renaissance were arrested and imprisoned or shot.\n\n`,
  },
  {
    title: "Deportation, arrests, executions (1933–1938)",
    text: `In 1927, Stalin abolished the New Economic Policy and turned to the forced industrialisation and the collectivization of agriculture of the First Five-Year Plan.\n\nChanges in cultural politics also occurred. An early example was the 1930 show trial of the "Union for the Freedom of Ukraine" at which 45 intellectuals, higher education professors, writers, a theologian and a priest were publicly prosecuted in Kharkiv, then capital of Soviet Ukraine. Fifteen of the accused were executed, many more with links to the defendants (248) were sent to the camps. (This was one of a series of contemporary show trials, held in the North Caucasus, 1929 in Shakhty, and in Moscow, the 1930 Industrial Party Trial and the 1931 Menshevik Trial.)\n\nThe systematic elimination of the Ukrainian intelligentsia dates back to May 1933 when Mykhailo Yalovyi was arrested; in response Mykola Khvylovy committed suicide in the "Slovo" (Word) Building in Kharkiv. The campaign ran from 1934 to 1940, reaching a peak during the Great Terror of 1937–1938. A total of 223 writers were arrested and in a number of cases imprisoned and shot. Almost three hundred representatives of the Ukrainian Renaissance of the 1920s and 1930s were shot between 27 October and 4 November 1937 at Sandarmokh, a massive killing field in Karelia (northwest Russia).\n\nSome important representatives of this generation survived. Many remained in the Soviet Union: Oleksandr Dovzhenko, Pavlo Tychyna, Maksym Rylskyi, Borys Antonenko-Davydovych, Ostap Vyshnia, and Mykola Bazhan. A few emigrated: Ulas Samchuk, George Shevelov, and Ivan Bahrianyi.\n\nThe scale of the tragedy\nExact figures for Ukrainian intellectuals imprisoned and executed during the Great Terror are not available. It is, by comparison, relatively straightfoward to determine how many writers were involved. The "Slovo" Association (Ukrainian writers in emigration) sent its assessment on 20 December 1954 to the Second All-Union Congress of Writers in the USSR: in 1930, works by 259 Ukrainian writers were in print; after 1938 only 36 writers were published (13.9% of the earlier total). According to "Slovo", 192 of the "missing" 223 writers were deported, sent to the Gulag or executed; a further 16 disappeared; and eight writers committed suicide.\n\nThese data are confirmed by The Altar of Sorrow (ed., Olexii Musiienko), a martyrology of Ukrainian writers, which numbers 246 writer-victims of Stalin's terror. Other sources indicate that 228 of 260 Ukrainian writers were deported, imprisoned or shot.`,
  },
];

export const AboutImagesUkr = [
  {
    path: "krushelnycki.jpeg",
    caption: `The Krushelnytskyi family, the beginning of the 1930s. Sitting (from left to right): Volodymyra, Taras, Maria (mother), Larisa and father Antin. Standing: Ostap, Galya (Ivan's wife), Ivan, Natalya (Bohdan's wife), Bohdan. In 1934-37 Volodymyra, Taras, Antin, Ostap, Ivan and Bohdan were repressed and executed. This photo became a symbol of the extermination of the Ukrainian intelligentsia by the Stalinist regime.`,
  },
];