export const poetsEng = [
  {
    name: "Maxym Rylsky",
    slug: "maxym-rylsky",
    deathYear: "1964",
    deathMonth: "7",
    startYear: "1907",
    imageFile: "rylsky.jpeg",
    years: "1895–1964",
    bio: "Rylsky, Maksym [Рильський, Максим; Ryl’s’kyj], b 19 March 1895 in Kyiv, d 24 July 1964 in Kyiv. Poet, translator, and community activist; full member of the Academy of Sciences of the Ukrainian SSR from 1943 and of the Academy of Sciences of the USSR from 1958; son of Tadei Rylsky. From 1944 until the end of his life he was director of the Institute of Fine Arts, Folklore, and Ethnography of the Academy of Sciences of the Ukrainian SSR. He studied at Kyiv University, initially in the medical faculty and later in the historical-philological faculty. Rylsky started to write early in life (he published his first poem in 1907), and by 1910 he had published his first youthful collection, Na bilykh ostrovakh (On the White Islands). The first mature collection to show his promise as an exceptional poet was Pid osinnimy zoriamy (Beneath the Autumn Stars, 1918). An abridged version, of half the original length, was published in 1926. The poetic talents of Rylsky reached full bloom with the publication of the collections Synia dalechin’ (The Blue Distance, 1922), Poemy (Poems, 1924), Kriz’ buriu i snih (Through Storm and Snow, 1925), Trynadtsiata vesna (The Thirteenth Spring, 1926), Homin i vidhomin (The Resonance and the Echo, 1929), and De skhodiat’sia dorohy (Where the Roads Meet, 1929).\n\nRylsky's lyric poetry grew out of the best achievements of Ukrainian poetry at his time, and out of his broad knowledge of world poetry, French writers in particular (especially the works of the Parnassians). He often used motifs and images from ancient mythology and adhered to classical forms, which practices linked him to the group of Neoclassicists. In many other respects, however, his philosophical and contemplative lyric poetry, with its wealth of moods and motifs of nature and of the individual becoming one with nature, did not fit the narrow definition of Neoclassicism. Rylsky's apolitical poetry provoked fierce attacks from official critics. He was arrested for a brief period in 1931, and then declared himself reformed and proclaimed his acceptance of the official Soviet view of reality in his collection Znak tereziv (The Sign of Libra, 1932). He alone of the Neoclassicists managed to live through the Stalinist terror and become one of the main poets in the ranks of the official Soviet versifiers. He became a member of the Party in 1943. In contrast to other official poets, however, he often expressed himself ambiguously in his eulogies of the Communist party, especially in those of Joseph Stalin.\n\nFrom the time he became an official poet, Rylsky published over 30 books of poetry. The major prewar works were Kyïv (Kyiv, 1935), Lito (Summer, 1936), Ukraïna (Ukraine, 1938), and Zbir vynohradu (The Harvest of Grapes, 1940). During the war and the evacuation of Soviet Ukrainian leaders to Ufa he published, among others, the collections, Za ridnu zemliu (For the Native Land, 1941), Slovo pro ridnu matir (A Song about My Mother, 1942), Zhaha (The Thirst, 1943), and Mandrivka v molodist’ (Journey into Youth, 1944). His numerous postwar collections include Chasha druzhby (The Cup of Friendship, 1946), Virnist’ (Fidelity, 1947), Pid zoriamy Kremlia (Beneath the Stars of the Kremlin, 1953), Na onovlenii zemli (On the Reclaimed Land, 1956), Holosiïvs’ka osin’ (Autumn in Holosiieve, 1959), and V zatinku zhaivoronka (In the Shade of the Lark, 1961).\n\nThroughout his literary career Rylsky also did many literary translations. An excellent example of his mastery of the art is his translation of Adam Mickiewicz's Pan Tadeusz. His translations from French are of a similarly high standard, from the classics of the 17th century to the poetry of Paul Verlaine, in particular the translations of Victor Hugo's Hernani, Edmond Rostand's Cyrano de Bergerac, and Voltaire's La Pucelle d'Orléans. He also translated William Shakespeare's King Lear and Twelfth Night, and Aleksandr Pushkin's Evgenii Onegin.\n\nLike most of the Soviet poets of the interwar generation, Rylsky did not manage to revitalize his writing at the beginning of ‘de-Stalinization,’ and his work remained merely technically proficient versification. Rylsky achieved much, however, in his role of community activist and publicist and contributed greatly to the brief literary rebirth of the early 1960s. In his essays and articles of that period, which are collected in publications such as Vechirni rozmovy (Evening Conversations, 1962) and Pro mystetstvo (On Art, 1962), he carefully and tactfully, though unflaggingly, defended Ukrainian culture against the pressure of Russification. Rylsky was not so much an innovator in Ukrainian poetry as a practitioner of classic verse, the sonnet form in particular. He contributed more than any of his contemporaries to the development of the Ukrainian literary language. His selected works have been published as Poeziï (Poems, 3 vols, 1946), Poeziï (Poems, 3 vols, 1949), Tvory (Works, 3 vols, 1956), and Tvory (Works, 10 vols, 1960–2; 20 vols, 1983–90).",
    poems: [],
    unavailable: "The poems have not been translated yet",
  },
  {
    name: "Yevhen Pluzhnyuk",
    slug: "yevhen-pluzhnyuk",
    deathYear: "1936",
    deathMonth: "12",
    startYear: "1924",
    imageFile: "pluzhnyk.jpeg",
    years: "1989–1936",
    bio: "Pluzhnyk, Yevhen [Плужник, Євген; Plužnyk, Jevhen], b 26 December 1898 in Kantemyrivka, Bohuchar county, Voronezh gubernia, d 31 January 1936 in the Solovets Islands. Writer. In the years 1923–8 he belonged to the Kyiv writers' groups Aspys, Lanka, and MARS and contributed poetry to several Soviet Ukrainian journals. During his lifetime he published only two poetry collections, Dni (Days) in 1926 and Rannia osin’ (Early Autumn) in 1927; a third, Rivnovaha (Equilibrium), first appeared posthumously in an émigré edition in Augsburg in 1948. He also wrote the novel Neduha (Illness, 1928), which was banned from circulation shortly after its publication. Two of his plays, Profesor Sukhorab and U dvori na peredmisti (In the Courtyard in the Suburb), appeared in Zhyttia i revoliutsiia in 1929; a drama in verse, ‘Shkidnyky’ (Wreckers), was never published. He also translated Russian literature into Ukrainian and compiled (with Valeriian Pidmohylny) a dictionary of Ukrainian official phraseology (1926) and (with Vasyl Atamaniuk and Feliks Yakubovsky) an anthology of Ukrainian poetry (1930–2).\nAlthough Pluzhnyk was one of the finest Ukrainian poets of the 1920s (he has been compared to Rainer Maria Rilke), Party criticism was hostile to his contemplative, laconic, and frequently gloomy lyricism and depiction of revolutionary atrocities and Soviet reality. After his novel was banned from circulation, he published very little. In December 1934 he was arrested together with many other Ukrainian figures, and in March 1935 he was sentenced by a military tribunal to death by firing squad. The verdict was commuted to 10 years' imprisonment in the Solovets Islands in the White Sea, where he soon died of the tuberculosis that had afflicted him since 1926. He was rehabilitated posthumously in 1956, and editions of his collected poems were published in Kyiv in 1966 and 1988. An uncensored edition appeared in Munich in 1979.",
    poems: [
      {
        title: "* * *",
        text: "I know that\nPloughshares are beaten out of swords. No soil becomes fertile because of\nThis art.\nSome keys there he that will afford Entrance into the entire heart. \n\nI perceive\nHow things are based:\nThrough all the wheat, blood is wove — Only thus people learn the taste\nOf love, \n\nI believe. \n",
      },
      {
        title: "* * *",
        text: "To learn wisdom — others don’t employ:\nAll mistakes must be your very own.\nWorks that have come down to us from Troy \nBorrowed were, for odes of ancient Rome.\n\nStudy well, even commas, by the way — \nAnd from each line a lesson you’ll partake: \nBetter make your own mistakes than, say, \nTry to learn from errors others make.",
      },
      {
        title: "* * *",
        text: "Night world in beauty wrought.\nNo symmetry. No utterance. Death inclined. \nSpeak not, then; speak not!\nWho or what throws words to the wind? \n\nAll the futility of a world beyond,\nAnd endless making of little worlds;\nHas not their meaning long been conned \nIn textbooks for the boys and girls! \nYet truly wrought in beauty — the night world! \n",
      },
      {
        title: "* * *",
        text: "Oh, when September-golden comes to pass \nAnd, like a laggard wandering,\nCaresses the silky fleece of autumn grass\nAnd cranes are gathered round a water-spring,\n\nAt night, I love to watch the deeper blue \nOf autumn's vaults of heaven draw\nThe raining stars, as carpenter would strew \nThe silvery shavings from his moving saw...\n\nWhat fiery light! For nature can afford\nFrom weariness to rest in beauty now released — \nWhich is perhaps in truth a high award\nFor summer's passion — grant of quiet peace.",
      },
      {
        title: "* * *",
        text: "Just a small town. But climb up the bell-tower — \nVista of rye fields and neighbouring farms,\nTown hall, houses, offices, drug-store —\nAll so familiar, all full of charm.\n\nI shall live quietly. \nLike when Fall is fair...\nAnd sit by my gate in the evenin’... \nOpposite lies the market square —\n\nThere play the dogs and the children.\nFolk don't need much, I know, to get by — \nJust a few memories, a room, some baccy — \nAnd sometimes a bit of blue sky.\nOr the Ninth symphony...",
      },
    ],
  },
  {
    name: "Pavlo Tychyna",
    slug: "pavlo-tychyna",
    years: "1891–1967",
    deathYear: "1967",
    bio: "Paulo Tychina (1891-1967) was born in the village of Pisky, Chernihiu Region, into the family of a deacon. One of the founders of new Soviet literature, he is the author of many books of verse, long poems, and poetry translations which won him nationwide recognition. His poetry is distinguished for its innovation, its wealth of themes, and profound insights into the inner world of Soviet man, the builder of communist society. His works have been translated into many Soviet and foreign languages. He also wrote a nurriber of scholarly works on Slavic, Oriental, and other literatures. Pavlo Tychina was a member of the Ukrainian SSR Academy of Sciences, corresponding member of the Academy of Sciences of Bulgaria, Hero of Socialist Labour, and a USSR State and Taras Shevchenko prize winner. The best literary works concerning the friendship of nations are annually awarded the Pavlo Tychina Prize.",
    poems: [
      {
        title: "HARPS RINGING, HARPS RINGING...",
        text: "Harps ringing, harps ringing —\ngolden ringing, loud resounding, through the \n            sing out your strings, \n         glad news echoing: \n      The fragrant spring’s \n      on the wing, \n   Flowering, dew-pearling, \n      painting every thing. \nThoughts flying, thoughts flying —\nlike a sea with white sails crowding, brim with \n               tender tones of blue, \n         flying thoughts that swirl: \n      Storms will come, \n      lightnings run! \n   Laughter be, weeping be \n   dews of mother-of-pearl... \nI arise, cast my eyes —\nrills all round like bells ajingle, larks pour down \n               in notes of gold \n            waterfalls that sing: \n      The fragrant spring’s \n      on the wing, \n   Flowering, dew-pearling, \n      painting every thing. \nLove of mine, heart of mine —\nshould you wander on the meadows all in sadness caught \n      or with joy awhirl: \n      Spare but one glance, 0 come! \n   Laughter be, weeping be \n      dews of mother-of-pearl. \n",
        year: "1914",
      },
      {
        title: "Pastels",
        text: "Runs by a bunny.\nStops to see —\nThe dawnlight!\nAnd plays gleefully.\nThe daisies open up their eyes. \nSunrise-perfumes touch the skies. \nCocks embroider the cloak of night With fiery threads of vocal light. \nSunrise.\nRuns by a bunny.\n\nII\n\nIt has supped on hearty wine —\nThe robust day.\n“Meadows, strew your flower blooms!” \n“Coming,” calls the Day.\n“0 flocks, feed on pastures!” \n“Seek your love,” calls lusty Day. \n“Sing your lullabies, wheat-ears!” calls Day.\nIt has supped on hearty wine — The robust day.\n\nIII\n\nTrills like flutes rang on horizons \nWhere the sun had gone to rest. On tip-toe\nCame quiet evening.\nStars came out, twinkling,\nThe mist crept over the meadows And, finger on lip, lay down to Sleep.\nTrills like flutes rang on horizons Where the sun had gone to rest.\n\nIV\n\nOh, wrap me up well. Oh, wrap me — Fin old, I’m night.\nAnd ailing fast.\nTo sleep my black road ran\nSince time began.\nMake a bed of mint for me;\nLet poplars rustle, lull with song.\nOh, wrap me up well. Oh, wrap me — I’m old, I’m night.\nAnd ailing fast.",
      },
    ],
    deathMonth: "9",
    startYear: "1912",
    imageFile: "pavlo-tychyna.jpeg",
  },
  {
    name: "Dmytro Zahul",
    slug: "dmytro-zahul",
    deathYear: "1944",
    deathMonth: "6",
    startYear: "1909",
    imageFile: "zahul.jpeg",
    years: "1890–1944",
    bio: "Zahul, Dmytro [Загул, Дмитро; pseuds: I. Maidan, B. Tyverets], b 28 August 1890 in Miliieve, Bukovyna, d 1944 in the Kolyma region. Writer. He belonged to the Muzahet group of symbolist poets. He later joined the Zakhidnia Ukraina group. His first published works appeared in the newspaper Bukovyna in 1907. Later he published in Hart, Hlobus, Zhyttia i revoliutsiia, Chervonyi shliakh, and other journals and almanacs. Collections of his poetry include Z zelenykh hir (From the Green Mountains, 1918), Na hrani (On the Edge, 1919), Nash den' (Our Day, 1923), Motyvy (Motifs, 1927), and the posthumous Vybrane (Selections, 1961). He also wrote a textbook on poetics, Poetyka (Poetics, 1923), a collection of essays in literary criticism, Literatura chy literaturshchyna? ( Literature or Literary Hackwork?, 1926), and a collection of translations, Vybir nimets'kykh baliad (A Selection of German Ballads, 1928). He was arrested on 26 February 1933 and sentenced to 10 years’ imprisonment in concentration camps. An edition of his poems was published in Kyiv in 1990.",
    poems: [
      {
        title: "I GAZE AFAR...",
        text: "I gaze afar on stormy seas\nwhere one white gull wingtips the waves, \nand, on the wind to infinities,\nmy thoughts race — like young pilot brave. \nOh, many a venture gay secretes\nmy heart, and for the doing craves.\n\nThe elements ring as if alive,\nand thunder claps beyond the mountain — \na storm of passion it revives:\npours in my heart a cloudburst fountain... \nLeap up, winged words, with power drive \nlike airplane from a runway mounting.\n\nWhere storm and terrors rage at sea, \nwhere winds on brow blow icily — \nlike bison mad, rush angrily\nat elemental mysteries...\nSuccess falls to the brave and free — \nso doth the screaming gull decree.\n\nUnwavering to far unknowns,\nlaunch forth your poem-boats, no plaints; \nopen your heart without constraint\nbut stir no slime whose lure intones —\nlet feelings be metal and run unrestrained \nthough arteries give and be broken.\n\nWhen melancholy —that green-eyed spleen — \nlike Moloch gapes its greedy maw,\nthe mind like an iron bell rings keen,\nin your heart the tocsin bespeaks the law:\nThat death inescapable waits unseen \nall submitting to hypochondria.\n\nStart up and shake your motor, \nHeart, win the right to happiness the while. \nRoads call you on to worlds apart\nlike the tender lure of a woman’s smile... \nBurst forth like lava, Stormy Bard,\nfrom volcanoes of grief and lone exile.\n\nLet your head reel round from the sparkling wine \nof whirlwind storm and ring of thunder.\nLet passions live once more, define\nthe breach in the struggle and break it asunder...! \nFly on, fly on, 0 songs of mine,\nyou are planes from my Port roaming younder.\n\nHigher and higher in stormy flight!\nPast blue horizons your vanes will wave, \nyoung pilot brave, in dreams of light... \nOh, many a venture comes in sight\nthat my heart so for the doing craves.\n\nI gaze on an ocean of stormy seas,\nwith ventures gay my coteries\nwhere the elements revel on musical staves.",
      },
    ],
  },
  {
    name: "Olexa Vlyzko",
    slug: "olexa-vlyzko",
    deathYear: "1934",
    deathMonth: "12",
    startYear: "1925",
    imageFile: "vlyzko.jpeg",
    years: "1908–1934",
    bio: "Vlyzko, Oleksa [Влизько, Олекса; Vlyz’ko], b 17 February 1908 in Korosten, Novgorod gubernia, Russia, d 14 December 1934 in Kyiv. Poet. He studied at the philological faculty of the Kyiv Institute of People's Education. He belonged to the literary organizations Molodniak and the All-Ukrainian Association of Proletarian Writers and later worked on the futurist journal Nova generatsiia. His first published poem was ‘Sertse na nord’ (Heart to the North) in the journal Hlobus (1925). Although Vlyzko paid the obligatory tribute to the Soviet way of life, his poetry was characterized by a search for new socialist forms of artistic expression, a cheerful romanticism, a love of the sea as a primal element, and interest in the adventures and passions of people of strong character. Vlyzko's poetry appeared in such collections as Za vsikh skazhu (I'll Speak on Everyone's Behalf, 1927), Poeziï (Poems, 1927), Zhyvu, pratsiuiu (I Live and I Work, 1930), Knyha baliad (The Book of Ballads, 1930), and P'iatyi korabel’ (Fifth Ship, 1933). In December 1934 he was arrested, accused of counterrevolutionary diversionary activities, and shot along with 28 other writers and cultural activists. During Nikita Khrushchev’s ‘thaw’ he was ‘rehabilitated.’ A posthumous collection was published in 1963, Vybrani poeziï (Selected Poems).",
    poems: [
      {
        title: "* * *",
        text: "Rich red blood, and my strength, open-handed \nLike Svyatogor, I would bring to the mass!.. \nAnd if hearts could but be expanded,\nI’d expand them a thousand times thus.\n\nAnd would scatter, would scatter, would scatter \nMy energy, like the bright sun’s rays,\nSo the world should catch fire, and batter\nAnd break down the bounds of ancient days!",
        year: "1927",
      },
      {
        title: "NINTH SYMPHONY",
        text: "Fire! Fire of superhuman love!\nIn youthful breasts let seethe the blood! \nI take you, oh my thorny world\nIn the sun’s embrace!\n            Like some warm bird \nMy fire-bird heart will fly around\nAll worlds. I’ll stretch o’er mankind’s bounds\n\nWide wings. Let fate be made beneath \nTheir shade. If men no heaven find,\nThey’ll find the hell-fire of young love, \nAll-human, strong, in which all wrong\nWill burn to ash — and that fierce heart \nBare-fanged, which drinks its brother’s gore \nWill fall, and never flourish more:\nThere’ll be no resurrecting it,\nJust as he’ll never rise, who falls \nInto those fierce and fiery jaws — \nThe human heart’s volcanic pit!..\n\nFire! Fire of superhuman storm!\nOf new love, wordless from the lips\nOf broken eunuchs, from the tongues\nOf hearts in gloves, that none, perhaps, \nShould see the skinny poisonous corpse \nWhere maggots breed —that noble dirt \nWhich rickety heirs have long preserved. \nDegenerates of the “true blue blood” \nWith blazoned arms of ancient homes. \nAnd suppuration ’neath golden cloaks!..\n\nFire! Fire of superhuman love!\nAlive for the strong, and dead for the dust. \nOf love impulsive and burning bright\nFor all things. Captivating might\nOf love for people, earth and beasts\nAs one. To live, to live like a sun!\nBy one’s own sweat true joy achieve\nFor one’s own sons, grandsons and heirs\nOf distant days!..\n         Fire! Fire of love!\nIn youthful breasts let seethe the blood!\n\nI take you, oh my thorny world\nIn the sun’s embrace! And in my love\nAs in fire, I place! Then burn with light\nAnd give to the poor blind wretch his sight, \nAnd blind the one, who the dark prefers, \nHimself inters in the graveyard mire!..\nMore sun, more light!! More love, more fire!!!",
        year: "1927",
      },
      {
        title: 'BALLAD OF "THE FLYING DUTCHMAN"',
        text: `The heavy\ncruiser\ngoes out\non her course.\nLike a rusty roof, \nthe land slowly goes. \nThe bridge. \nThe Captain.\nThe Devil’s own curse \non his evil lips,\nthe Zeiss\non his nose. \n\nIn his fury\nhe wrinkles\nhis frowning brow... \nAbove the horizon\nthe sun\nand blue haze;\nlike toad’s eyes\npeer the gun-barrels now, \ntheir steel beaks\nskyward\nthey raise.\nThere’s distant thunder. \nA choppy sea.\nThe warm foam\nchatters\nand spatters the deck. \nThe anchor rings.\nIn the foc’sle lee \nthe trap-ladder grates\nwith a quiet squeak... \n\nThe ocean lies dumb \nin the azure haze... \nA sudden\norder: \n“Change course! \nDue west!” \nAbove the horizon \na mast \nand cross-stays,\nwith a flag\nblood-red\n’gainst the blue impressed... \n\n\nAnd sharp\nas a jack-knife\nthat terse quick glance — \nand lieutenants\ndash up,\ntheir grins can't withhold, \nupon that ship,\non the tattered yards\nare strung up\ncorpses...\nB-r-r-r\nHow cold! \n\nStill nearer...\nStill nearer...\nThe horror grows... \nAnd the stench\nfloats over\nthe cruiser’s course... \nOn a light breeze \nsprung up\nit flows...\n“Reverse!\nAbout ship!”\nthe Captain roars.\nThe ship disappeared... \nA chill\nshook their bones...\nand as soon\nas night\non the foc’s’le\nfell,\na shivering sailor,\nin lowered tones\nof the “Flying Dutchman” \nbegan\nto tell...\nOn the waves\nthe wind\nhis bellows blew...\nAnd, bent o’er the bridge, \nand peering beneath,\nthe Captain listened.\nHis laughter flew\nlike a devil,\nin spasms,\nbetween his teeth: \n\n“The Flying Dutchman”?! \nHa-ha-ha! \nThey were Communards \nhung on that brig!\nhe cried.\nAnd suddenly, \nlosing his legs with a jar,\nin his twisted guts \nthe laughter \ndied,.. \n\nIn his fury\nhe wrinkles\nhis frowning brow... \nAbove the horizon\nthe gold,\nand blue haze;\nand like toad’s eyes\npeer the gun-barrels now, \ntheir steel beaks\nskyward\nthey gaping raise. \nThere’s distant thunder. \nA choppy sea.\nThe fine rain\nchatters\nand spatters the deck. \nThe anchor rings. \nIn the foc’s’le lee \nthe trap-ladder \nmockingly grates \nwith a squeak. \n\n\n`,
        year: "1930",
      },
    ],
  },
  {
    name: "Vasyl Mysyk",
    slug: "vasyl-mysyk",
    deathYear: "1983",
    deathMonth: "3",
    startYear: "1923",
    imageFile: "mysyk.jpeg",
    years: "1907–1983",
    bio: "Mysyk, Vasyl [Мисик, Василь], b 24 July 1907 in Novopavlivka, Katerynoslav gubernia, d 3 March 1983 in Kharkiv. Writer and translator. He debuted as a poet in Chervonyi shliakh in 1923. From 1924 he lived in Kharkiv, where he belonged to the writers' groups Pluh and Prolitfront, contributed to Literaturnyi iarmarok, studied English, German, and Persian, and published the poetry collections Travy (Grasses, 1927), Blakytnyi mist (The Azure Bridge, 1929), Chotyry vitry (The Four Winds, 1930), Turksyb (1932), and Budivnyky (Builders, 1933) and the story collection Galaganiv son (Galagan's Dream, 1930). After visiting Central Asia he wrote the essay collections Tysiachi kilometriv (Thousands of Kilometers, 1931) and Kazakhstans’ka magistral’ (The Kazakhstan Trunk Line, 1931). He was arrested during the Stalinist terror in December 1934 and was imprisoned in labor camps in the Soviet Arctic until 1940. From 1942 to 1945 he was in a German concentration camp for Soviet prisoners of war. After being ‘rehabilitated’ in 1956, he published editions of his selected works (1958, 1967, 1977), the new collections Borozny (Furrows, 1962), Verkhovittia (Top Branches, 1963), Chornotrop (The Snow-free Way, 1966), Lan (The Farmland, 1970), and Bereh (The Shore, 1972), and the story collection Brians’kyi lis (Briansk Forest, 1978). He became a leading translator of English, American, German, and Persian literature. Published separately were his translations of the poetry of Robert Burns (1932), Rudaki (1962), Omar Khayyam (1965), John Keats (1968), Hafez (1971), and Firdousi (1975). A book of his articles and essays was published in 1982, and a collection of memoirs about him and V. Khytruk's literary biography appeared in 1987.",
    poems: [
      {
        title: "THE SPIRIT OF TODAY",
        text: "Thus in Boyan’s  age too, no doubt,\nWith flowers was the spring decked out, \nBeyond the Dnieper stormclouds massed \nAnd mountain torrents foamed and flashed, \nHawks vanished over the horizon\nAnd dulcimers were melodizing,\nIn virgin forests lakes were blue\nAnd gazed on crystal skies sublime.\nThen where’s the spirit of our time?\nIt’s here in what most matters — you.",
      },
      {
        title: "WORMWOOD",
        text: "Wormwood, I’m longing to know \nWhy of all herbs you alone\nWere born so bitter?\nHave you not drunk in sweet showers, \nBeen dew-bathed in the small hours When the fields glitter?\n\n\nOr from the bitter years past\nHave you drop by drop amassed \nSweat and blood of your forefathers \nWhich to this day you are guarding?\nYou came to love our steep slopes,\nRocky ravines and cool valleys.\nYour bitter taste every day\nMilch cows would bring from their pastures. \nInto the ryefield you crept,\nAround the stalks pressing,\nSo age-old gall may be sensed\nIn the bread of the steppelands...",
      },
      {
        title: "CRANES OF HIROSHIMA",
        text: "\nIf you yourself were a physician \nCould even you have calmly gazed \nUpon this little girl, a cripple\nAnd doomed to be so all her days?\nA girl for whom in sad grey autumn \nThe seasons of the year had stopped \nEver since over Hiroshima\nThe first atomic bomb was dropped.\n\nHow frightening, how long in passing \nWere nights with or without a moon! “\nShall I get well?” she kept on asking \nAnd people said to her: “Quite soon — \nAs soon as you have cut from paper \nFive thousand little birds... \nThese cranes \nShall fly high and prevent the raven \n\nFrom coming with that bomb again.”\nThey gave the girl a pair of scissors, \nWhite sheets of paper too they brought. \nA sudden smile her face transfigured, \nShe was no longer so distraught.\nShe wished her hands were not so feeble \nAnd that her eyes could better see.\nBut, hearing of her problem, people \nCame to assist her readily.\nAnd waking in the morning early \nThe little patient was surprised:\n \nWhere yesterday there had been merely \nA few birds, hundreds met her eyes! \nAnd every day in growing numbers \nBirds came to her from far and near... \nBut day by day her forces crumbled,\nOf no avail the cranes were here.\nNow there was nobody to see them. \nThey had not rid her of her pains.\nAnd what indeed could the physician\nDo now with all these paper cranes, \nWith these white flocks, her consolation, \nThat lightly fluttered as they went, \nRelentlessly incriminating\nAll murderers impenitent?",
      },
    ],
  },
  {
    name: "Mykola Bazhan",
    slug: "mykola-bazhan",
    deathYear: "1983",
    deathMonth: "11",
    startYear: "1923",
    imageFile: "bazhan.jpeg",
    years: "1904–1983",
    bio: "Bazhan, Mykola [Bažan], b 9 October 1904 in Kamianets-Podilskyi, d 23 November 1983 in Kyiv. (Photo: Mykola Bazhan.) Poet, writer, translator, and Soviet Ukrainian political and cultural figure; full member of the Academy of Sciences of the Ukrainian SSR from 1951. One of the most prominent representatives of the literary renaissance of the 1920s, he wrote screenplays, edited the journal Kino, and was associated with the literary groups Vaplite and Nova Generatsiia and the journal Literaturnyi iarmarok. Bazhan's poems were first published in 1923, but he gained recognition for the collections 17-i patrul' (The 17th Patrol, 1926). With Riz'blena tin' (The Sculptured Shadow, 1927), and especially Budivli (Buildings, 1929), Bazhan abandoned futurism and constructivism and emerged as a romantic expressionist, whose poems were characterized by dynamism, unusual imagery, monumentalism, and frequent references to the Ukrainian past.\n\nIn the poem ‘Budivli’ Bazhan treats historical themes, seeking a link between the modern era, the Middle Ages, and the Ukrainian baroque of the Cossack state. ‘Budivli’ and the poems ‘Rozmova serdets' ’(Heart-to-Heart Talk), in which he presented an unusually harsh assessment of Russia, ‘Hofmanova nich’ (Hoffman's Night, 1929), ‘Sliptsi’ (The Blind Beggars, 1933), ‘Trylohiia prystrasty’ (Trilogy of Passion, 1933), and others display an original poetic style: a bold statement of theme, a rich vocabulary replete with archaisms, syntactic complexity, an abundance of metaphor, and inventive rhyme. These poems, as well as the collections Doroha (The Road, 1930) and Poeziï (Poems, 1930), aroused harsh criticism of Bazhan: he was accused of ‘detachment from Soviet reality’, ‘idealism’, and nationalism.\n\nDuring the terror of 1934–7 Bazhan wrote the trilogy Bezsmertia (Immortality, 1935–7), which was dedicated to S. Kirov, and entered the company of poets enjoying official recognition. His later works, written in the spirit of Stalinist patriotism, all belong to the corpus of official Soviet poetry. These include the collections Bat’ky i syny (Fathers and Sons, 1938), Iamby (Iambs, 1940), Klych vozhdia (The Call of the Leader, 1942), and V dni viiny (In the Days of War, 1945); the collections awarded the Stalin Prize — Kliatva (Oath, 1941), Danylo Halyts’kyi (Danylo of Halych, 1942), Stalinhrads’kyi zoshyt (Stalingrad Notebook, 1943), and Anhliis’ki vrazhennia (English Impressions, 1948); and the collections Virshi i poemy (Poetry and Long Poems, 1949), Bilia Spas’koï vezhi (Near the Savior's Tower, 1952), Ioho im’ia (His Name, 1952), Honets (The Chaser, 1954), Iednist’ (Unity, 1954), Tvory (Works, 1946–7), and Vybrane (Selected Works, 1951, from which poems of the early period were omitted). After Joseph Stalin's death Bazhan did not take part in the cultural renaissance launched by the shistdesiatnyky (poets of the sixties); his later collections and poems, Iasa (1960), Italiis’ki zustrichi (Meetings in Italy, 1961), Polit kriz' buriu (Flight through the Storm, 1964, for which he received the Shevchenko Prize [see Prizes and awards]), Umans’ki spohady (Memories of Uman, 1972), Nichni rozdumy staroho maistra (Nocturnal Reflections of an Old Master, 1976), and others, were also written in the spirit of Party ideology. Bazhan's translation of S. Rustaveli's poem Vytiaz' u tyhrovii shkuri (The Knight in the Tiger Skin, 1927) was published to great critical acclaim, and he has produced many masterful translations from Georgian, Russian, and Polish, as well as of the poetry of Rainer Maria Rilke. Bazhan is also the author of literary studies, reviews, and memoirs.\n\nWith the outbreak of war in 1941 Bazhan emerged as a leading political figure. He was editor of the newspaper Za Radians’ku Ukraïnu!, deputy chairman of the Council of Ministers of the Ukrainian SSR (1943–8), a long-term member of the Central Committee of the Communist Party of Ukraine and deputy of the Supreme Soviet of the Ukrainian SSR and of the USSR, and head of the Writers' Union of Ukraine (1953–9). From 1958 he headed the editorial board of the Ukrainian Soviet Encyclopedia publishing house and served as editor-in-chief of many of its publications.",
    poems: [
      {
        title: "The Trooper's Song",
        text: "The troop cavalcade moved out, horses neighed, \n(Dully rings the steel in the stirrup-rest)\nSmoke from fields is acrid,\n                          field-smoke a rust-shade,\nFoam from horses’ lips — feather grass suggests. \nThrough winding leafy wood,\n                           the troop rode forward, \nIron hoof-heats hammer a way through the brush,\nThe clatter of sabre, the ring of the scabbard \nRupture the ominous hush.\n\nShading eyes, sheepskin hats highly towered, \nTroopers gulped the field scents, sweet and rank, \nTheir rough working hands smelled of powder, \nTheir cowhide coats too — of blood stank.\n\nOne slumped in saddle. I know you recall \nThe girl who’s your heart’s shining light. \nSo love, comrade mine, so love, but recall \nYour gun’s ready loaded to fight.\n\nThe soldiers must not sleep on sentry-go, \nNor their looks betray they are weary — \nWhat usefulness could such a soldier show \nAs sentry?\n\nNow you are their avengers, \nAnd will always be avengers \nOf your tormented brothers \nAnd your violated sisters.\n\nShow respect, show respect, render honours \nTo the names of the famous Red Guards, \nGuard and honour your regiment’s colours — \nFor the way of a hero is hard.\n\nWhen you hear but one shot of the foe, \nGrab your gun, to horse and mount! \nAnd the moment your enemies show, \nRide them down!\n\nSpurring madly his mount, \nA trooper rides in pursuit — \nHis rounds he won’t count, \nNor for wounds care a hoot.\n\nLet the roads not deter, \nThough you die, to boot — \nPut heart in your spurs \nAnd be ready to shoot!\n\nLet the wind lash your face, \nAnd die, but don’t stop! \nHell for leather we race \nAnd fight till we drop.\n\nDon’t wait for orders: \nWho wavers, death finds! \nHundreds of sabres\nCut through the wind.\n\nWe would twice over die the death,\nFor the rich black coal, for dark rye bread;\nFor workers’ black hands, gladly risk our heads — \nAnd would twice over die the death.",
        year: "1925",
      },
      {
        title: "Hoffman's night",
        text: "\nInto a dark abyss, down steps worn-down, rough-caiwen, \nDown slippery inclines, down heavy, risky stairs,\nDown rough-hewn steps, into the filthiest of lairs,\nA fat-paunched basement, a most dingy tavern,\n \nA den without a signboard or a name,\nRefuge of crazy burghers, hungry tramps,\nOf dreamers, cabmen, dames of evil fame,\nPursuing sinful inspiration, in he stamps...\nHalf-buried in the earth, its entrance gapes beneath — \nA drunkard’s sour-breathed mouth, where, like bad teeth, \nStick candles pouring yellow grease from every wick \nUpon the tables set with mugs heavy and thick\nAs if great fists, round, swollen, far from feeble,\nLike hefty apples — fruit of good and evil,\nThey stand upon the tables, bulging, knotted,\nTin mugs with liquor, smeared with dirt and spotted. \nThe tables creak and sway and dully shine,\nFingered and fouled and stained with fat and wine\nBy animals befuddled and besotted.\nFoul-smelling tallow hisses on the handles\nAnd necks of candlesticks with melting candles.\nThe secret rites of thoughtful drinking bouts\nAnd pompous banquets here are carried out,\nEach drunkard a philosopher, fanatic —\nSerapio’s brother — lunatic, frenetic.\nDrinking and laughing, Amadeus spends\nHere countless nights among his bosom friends,\nPoet of caustic words and crazy escapades\nKing of these solemnly insane assemblies\nWhich somewhat to a funeral bear resemblance,\nAnd before which, indeed, description fades.\nHere now he sits, a Mephistopheles half-sized,\nAnd over dark, ungodly feasts presides,\nOblivious, not caring in the least\nAbout his wife’s shoes, or official ranks and orders, \nSwallowing rancid smoke, wine and saliva, wordless, \nArching his eyebrow, sharp as a bare nerve,\nBending in wicked silence, full of verve,\nLike a predacious cat, his lean, lascivious spine.\nAnd so he sits — a giant cat, insidious and sly,\nA fancy-tortured maniac escorted\nBy poets, roisterers, with grimaces contorted,\nBoth sanctimonious and devilish at once,\nA sage and wizard, harlequin and dunce;\nIt’s he — the huge cat, kindest Pussy Murr,\nArching his back, showing his claws — for sure! —\nHere, in this tavern blind where smoke-wreathes drift,\nAt home, at magistrates, at the dull \nKammergericht.\nA theatre of monstrosities, drunk cripples\nHere opens for the dreamer while he tipples\nAnd in contempt the dented eyebrow bends,\nAnd through his gums, unleashed, his sharp tongue sends: “\nNo, I’m not drunk — \nI’m generous as one doomed.\nHey, bring us candles! \nLight the fire! \nAway with gloom!\n\n \nWine! \nBring us sugar, spirit, lemon-peel,\nAnd here’s to poetry! \nLet’s drink until we reel.\nCome, light the spirit in a grand auto-da-fe —\nLet it flare up — in lieu of Christian souls.\nScream, crazy oracles, between the wallsOf Berlin’s barmy, blasphemous cafe!”\nHot foams the sparkling punch, and blue flames quiver, gay. \nLike living tongues, they leap into the air,\nAbove the gleaming cauldron’s mouth they play.\n“Punch for our \nTheodore, gentlemen!” declare\nHis tipsy colleagues. “Truth and inspiration\nAre to be found in wine alone, sirs, since creation!”\nAnd like the fires lit by the Holy Inquisition\nGlows the cold sheen of wine, hot, fiery, scalding;\n“Now, colleagues, let’s drink from this buxom cauldron\nThe infernal fluid, though it bring us to perdition!”\nThe poison-cups boil hot, the liquor steams,\nLike poking fingers rise the bright blue flames,\nAnd over them, besotted, drunk to madness,\nWhirl spectres in the darkness — smoky shadows, \nBlurred images arise in his sick fancy,\nLike red lamps — wine-flushed faces, reeling, dancing; \nThe noble rapiers of blue candleflames point up:\nA carnival of ghosts born from the midnight cup!\nIn awful silence words like lightning flash\nFrom caved-in mouths: like blades the lips they slash. \nAnd words roll off the cliffs of phrases into madness \nLike chunks of rock into a precipice; '\nFlames rise in pillars and like serpents hiss,\nThe tables shake and groan as if in sadness.\n“Ha, cunning soul, once more \nI’ve snatched from death \nA stormy night lit up by wine and inspiration.\nI heave it on my back, catching my breath —\nA cross of shame, a black sign of damnation,\nAnd mercilessly, till the break of day,\nMy own dead corpse, my own poor lifeless clay Necrophilewise, \nI maim and torture, full of evil,\nIn shame, disgust, insanity and fever.\nAnd now I order to the ghosts of words:\nFrom the abyss of consciousness in herds,\nFrom the black pits of human minds crawl out\nLike spiders, in a slimy, hairy crowd,\nBearing within your bodies’ poison dread,\nThrough cracks of crippled thought out of my head, \nThat, poet, hypocrite, blasphemer, leper,\nYour corpses I might put on frightened paper\nAnd that my wizened skull might swell and split\nAnd stick vile fancy-tentacles from its black pit,\nAnd then, gripped in my fingers, with a shriek,\n \nMy pen should pounce upon the glossy, tear-damped sheet \nAnd in the creaky manuscript entomb\nHeinous visions born of inner gloom.\nWine, brothers! \nPour me out a glass of wine!\nLet foaming cauldrons boil again and gleam!\nLet wine-springs gush, and let their amber stream \nThick, crystal-clear, pour forth in sprays sublime! \nCome, Inspiration, visit me this night,\nI yearn for your seductive, foul delight!”\nHis angry heart tosses upon its chain,\nAccursed roamer, tearing forth again.\nAnd from an old friend’s hands a glass he takes\nAnd with the foaming wine his thirst he slakes.\nHis partners shout, and he stands listening,\nMad \nAmadeus, with his wine-glass glistening.\nBut, crab-like, with its poisoned stranglehold, \nWeariness grabs the drinkers’ bare, sore throats. \nExhausted with the wine and words, he now makes bold \nTo finish the satanic feast with one last toast.\nThe tar-soaked shag he crumples in his cold\nDamp palm with concentration. \nWhile still fumes\nThe fiery liquor in the cauldrons seething hot,\nAnd round the table settles silent gloom,\nA sleepy servant-girl in careless hands has brought \nNew pouchfuls of tobacco, greasy, curly.\nFrom porcelain pipes tobacco-wreaths come whirling; \nLong pipe-stems growl in mouths already hoarse.\n0 best-beloved time when without words\nFloat drowzy dreams and thoughts dim, jumbled, glide! \nWith pipes pressed in their lips like clarinets,\nSucking the luscious juice in viscous jets,\nThe poets sit there, thoughtful, pacified.\n0 music of long pipes, tobacco-melodies,\nBlue pirouettes of upward-flying wreaths!\nNow, inspiration, thoughts, death, chatter — disappear! \nKind German devil — he won’t make them quake with fear!\nWhere are the notes, Herr Hoffmann? Where are Haydn’s concertos? \nMaestro, to the clavicord!” For certain He’ll play them something perfect.\nHis pale fingers long to grip \nThe melody, to give it warmth, to shake alive the old musician!\nAnd he stands up, and smoke — a flag-like strip\nSpread by the faithful wind, curls at the feet of the magician. \nHe puts his hairy right hand on the white\nJaws of the keyboard, tamed to do his will.\nThe clock strikes twelve, though. \nCloser, closer still\nIts two black fingers press as if a rite\nOf swearing-in they were to carry out this night\nFor a new member of \nSerapio’s fraternity,\n \nThose fingers dipped in sacred \nTime ’neath \nSilence's dark hood. \nAnd then says he:\n“Gentlemen, time to leave! \nHo, there! Where are our cloaks? \nFriends, let us not be overly romantic!\nIt’s raining in the street!”\nAgain the shower soaks \nAnd scrapes like pens on paper, grim, pedantic;\nThe rain is decorating old \nBerlin In gothic letters, in a cassock of black rain.\nWho is it tearing through the prickly drops down the dark lane, \nThrough bushes thick, to fear not giving in?\n’Tis Chancellor Hoffmann hopping over puddles\nIn a delirious half-sleep, with wine and shag befuddled.\nThe street behind him like a gamut, long and even\nFloats, whirls and fades away, no traces leaving\nIn Amadeus’ confused, besotted brain\nThe flat squares are all overgrown with rain,\nMobile yet immobile, bush after soaking bush\nOver the drunkard, artiste, madman — goes \nSwoosh-Swoosh! Ah, colonnades of thin-stemmed, streaking rain,\nAh, rain, chimeric all in slots and arrows!\nSwing and splash up again, swing and play havoc\nOn that triangular old housefront so well known,\nThat house with his true wife and his hot-water-bottle,\nHis nightcap and his cotton dressing gown,\nThe big stove and the smell, so pleasant, floating\nOver the*copper censer with half-sour incense;\n“Amalia! Are you sleeping? Come, have sense!Open the door! \nDid you not hear the triple knock?”\n“Off with these shoes, now! \nDon’t bring any mud in!”\nThe door is opened and upstairs he clambers, thudding.\nShe puts his shoes beside the stove to dry\nWhile \nAmadeus, musing, chuckles on the sly,\nAnd from the stove’s glazed tiles smile, rosy-faced\nYoung knights and maidens, chubby, azure-laced\nAnd a fat swain coloured in cinnabar and white,\n(Glazed tiles — the \nDutch stonemason’s sole delight!) \nClasping his worthy sweetheart tight\nAlso smiles courteously; dreamy, quiet,\nThe hot dutch stove with flowers, birds and bows \nLike a well fed young wench, stands, never cooling. \nThe oily glaze melts, the fat satellites in rows\nShine bright with cochineal, lapis-lazuli.\nThe floors creak stolidly, and doors squeal everywhere. \nHoffmann takes refuge in his room — his old abode \nWhere on an old pot-bellied secretaire\nWait his winged pen, his inkwell, deep and broad.",
      },
    ],
  },
  {
    name: "Mykhailo Drai-Khmara",
    slug: "mykhailo-drai-khmara",
    deathYear: "1939",
    deathMonth: "1",
    startYear: "1922",
    imageFile: "khmara.jpg",
    years: "1889–1939",
    bio: `Mykhailo Drai-Khmara (1889-1939) was a Ukrainian poet, linguist, scholar and academic and one of the many major authors who died during the Soviet state's genocide of Ukraine in the 1930's. He was also a prolific translator, who recast Dante's "Inferno" into Ukrainian along with works by many other major European authors. However his sonnet Swans (1928), which celebrated Ukraine's five leading neoclassical poets, challenged the Soviet state's attempt to destroy Ukrainian culture. This beautiful poem initiated his fight against the authorities and was the beginning of the path that led to his death in a labour camp in Kolyma in 1939. It is believed that he laid down his life to save that of another prisoner.`,
    poems: [
      {
        title: "These Lips of Stone",
        text: "These lips of stone\n                      The tall rooftops\nGulping the curdled light\nLike Tatar Boza\nThe bee swarm clings to a vast honeycomb\n               Unmoving.\n               Its massive sleep.\nSwollen eyelids blink\nBeyond the city’s periphery\nFingers drum the guttering nervously.\nBoulevards\nSnow veined with dirt\n                                     Antique marble\nDarkening around tree stumps,\n                                    Wounds collapsing inwards\nThese tears that are not mine\nBut those of oaks fallen\nMy face and hands sprinkled with rain.\nWhy do you weep, blind ones\nLet the road\n                    Be covered with this dirty fabric\nLet it displace\n                      The pendent ice\n                      And believe\n              Soon soon\nThe rainbow will come\nSpring will chime\nIn the poorest dwelling,\n               Sunlight will festoon\n               Roses, though silently now\n               People in winter coats\n               Drift on sleighs through snow.",
      },
      {
        title: "Swans",
        text: "On the tranquil lake where willows dream\nLong tamed by both summer and Autumn\nThey splashdown,   flutter and swim \nTheir necks bend like heavily laden vines.\nWhen frosts come resonant as glass\nAnd waves whisper immersed in a white trance\nThese swimmers shatter the frozen space\nFearless, although winter threatens.\nOh cluster of five unconquered singers\nThrough snow and storm your song victorious\nBreaks the apathetic faithless ice.\nBe strong; from slavery and nothingness\nBe guided by the constellated Lyre\nTo worlds of light, oceans of foaming life.",
      },
    ],
  },
  {
    name: "Bohdan Ihor Antonych",
    slug: "bohdan-ihor-antonych",
    deathYear: "1937",
    deathMonth: "7",
    startYear: "1931",
    imageFile: "antonych.jpeg",
    years: "1909-1937",
    bio: "Antonych, Bohdan Ihor [Antonyč], b 5 October 1909 in Novytsia, Gorlice county in the Lemko region, d 6 July 1937 in Lviv. (Photo: Bohdan Ihor Antonych.) Poet, critic, and publicist. As a student in the arts and science faculty of Lviv University, Antonych assiduously studied the Ukrainian language and Ukrainian literature and wrote journalistic and critical articles under the pseudonym Zoil. He graduated in 1933. With V. Havryliuk and Volodymyr Lasovsky he co-edited the art journal Karby. Antonych edited the literary chronicle for the journal Dazhboh and for a time was its editor in chief. According to his own admission, Antonych was ‘a pagan in love with life,’ ‘a poet of spring intoxication.’ His lyrical poetry deals with a wide range of philosophical themes and combines the principles of imagism with a unique form of pantheism rooted in Lemko folklore. His religious attitude to folk objects and his extensive use of alliteration fascinated his contemporaries and have influenced later poets, notably Ihor Kalynets and Mykola Horbal.\n\nAntonych wrote the poetry collections: Pryvitannia zhyttia (Welcoming Life, 1931), Try persteni (Three Rings, 1934), and Knyha leva (The Book of the Lion, 1936). Zelena Ievanheliia (The Green Gospel, 1938), Rotatsiï (Rotations, 1938), and Vybrani poeziï (Selected Poems, ed Bohdan Romanenchuk, 1940) were published posthumously. In the 1960s there was renewed interest in Antonych's poetry. Various articles on and studies of his work appeared. Several annotated editions of his poetry were published: Persteni molodosti (The Rings of Youth, Bratislava 1966), Pisnia pro neznyshchennist' materiï (Song on the Indestructibility of Matter, Kyiv 1967), and Zibrani tvory (The Collected Works, ed Sviatoslav Hordynsky and Bohdan Rubchak, New York-Winnipeg 1967). The last collection includes, besides Antonych's poetry, his unfinished libretto Dovbush, fragments of the novel Na tomu berezi (On the Other Shore), his theoretical articles on art, journalistic articles, and book reviews. In the 1970s selections from his work were translated into Slovak (Očareny pohan [Košice 1976]) and into English (Square of Angels [New York 1977]). A bibliography of Antonych’s works, compiled by T. Kulchytska and N. Hraitser, appeared in 1989.",
    poems: [],
    unavailable: "The poems have not been translated yet",
  },
  {
    name: "Volodymyr Svidzinsky",
    slug: "volodymyr-svidzinsky",
    deathYear: "1941",
    deathMonth: "10",
    startYear: "1912",
    imageFile: "svidzynsky.jpg",
    years: "1885–1941",
    bio: "Svidzinsky, Volodymyr [Svidzins’kyj] (Svidzynsky), b 9 October 1885 in Maianiv, Vinnytsia county, Podilia gubernia, d 18 October 1941. (Photo: Volodymyr Svidzinsky.) Poet and translator. His first collection, Lirychni poeziï (Lyrical Poetry), was published in 1922; it was followed by Veresen’ (September 1927) and Poeziï (Poems, ed Yurii Yanovsky, 1940). His poems, written in 1927–36 and printed in Ukraine in the years 1937–40, were collected by Oleksa Veretenchenko and published in Munich in 1975 in the collection Medobir (Honey Wood). Poeziï (Poems, 1986) was a more recent edition of his work published in Ukraine. His collected poems and translations in two volumes were published in Kyiv in 2004. In his early collections Svidzynsky leaned toward symbolism, but in the two last collections there are elements of surrealism combined with classical forms. An important part of Svidzinsky's work is stories with folk or exotic motifs; there are also translations from the classics (Hesiod, Aesop, Ovid, Aristophanes) and from French, German, Polish, and Russian poetry. Svidzinsky died while under arrest, during the evacuation of Kharkiv in the fall of 1941. (According to eyewitness accounts, he was burned alive together with other prisoners in Saltiv, near Kharkiv. According to Soviet records, he was killed by a German bomb.)",
    poems: [
      {
        title: "The Lustre of Surfaces",
        text: "The lustre of surfaces dies into the shadow\nAnd antique silence sleeps,\nLike water decanted into a bowl.\nOnly my hands live,\nStrange and separate,\nTheir movements\nCompel me to meditate,\nLike the whisper of a leaf.\nI go to the window,\nA broken post stands by the verandah,\nMould grows in the guttering\nWhere snowflakes gather in winter,\nWhere birds alight in the morning.\nI press my forehead against the glass\nAnd gaze for a while.\nI don’t love the advent of night\nIt seems guilty, a dark linen,\nThe blurred green edges of vegetation.\nA huge pool of silence accumulates.\nWhere have the birds gone?\nThe lustrous surface of things dies,\nThe curtains hang motionless\nAs if carved in stone.\nIn my defined circle of silence\nI become more insensitive, and sad,\nAs a forgotten, Chinese lantern caught\nOn a branch in some old orchard.",
      },
      {
        title: `From "Treachery"`,
        text: "In the western fields at dusk\nThe ash doesn’t whisper\nThe jasmine is not fragrant\nAs at first light.\nHow  gently\nYou come over the horizon\nTo the violet in the glade.\nYou step towards her\nThe earth crackling\nWith autumn ice underfoot,\nAnd look beyond the path\nTo see grassy mounds\nSquat like bazaar stallholders\nSome solitary and others in pairs\nAnd the jasmine fades\nIn the yellow hands of buckthorn.\nCome\nWe will embrace you in auburn waters\nSwathe you in tangled grass\nGive you a maiden\nGreen of shoulder, smooth of belly\nLustrous eyed, the marsh’s beauty…”\nThe violet smiles\nAt how easily you are lured.\nThe silence is morose suddenly\nA maiden straight and tall\nYou stretch out your hand,\nShe is the night you call.\n",
      },
      {
        title: "Where wild chicory covered the street",
        text: "Where wild chicory covered the street\nIn a familiar circle\nWhere I would not place my feet\nThe doors were open\nBut only the night entered\nLimping clumsily\nAnd wearing no pale blue hat\nWith a zig-zag of grey silk.\nI embraced her before I spoke\n“Sweetheart how long I waited\nBy your window, when day came\nIt was not I troubling the branches\nOf mountain ash and cherry trees.”\nThe night leaves at dawn\nWith her friend the moon\nThey will sit together\nOn the shaking cart of sunlight\nWhen the orchids flutter\nAnd I’ll look from my verandah.\nDo not look at me or mock the night\nWith its deformed feet.\n",
      },
      {
        title: "I walk alongside the stream",
        text: "I walk alongside the stream\nA bird’s wings flash in the dusk\nDarkness thatches its shadow\nOn crag and alder.\nI walk alone…\nTense my forgotten hands\nWill I hear the fairy-tale whisper\nOf someone’s love.\nBut all around are familiar shapes,\nDarkness lisps mockingly\nThat I walk home\nThrough no fabled landscapes\nNo stories come. ",
      },
      {
        title: "It is already evening, a soft breeze",
        text: "It is already evening, a soft breeze\nBehind the leafless tree in the orchard\n(As if these two trees are not kindred)\nThe willow branches blossom\nWith a candle’s yellow flame\nLit for spring, its juvenile roar.\nWhy does it burn?\nIt is evening with a soft breeze,\nDo you see black horses to the east\nDressed as for some antique funeral\nEmerging from the dusk?\nThey will bear you back quietly\nAs the yellow flame is severed\nFrom the willow branch\nTo limp after them,\nIn dishevelled smoke will come\nTo the locked hollowness and bow\nWhere the north is blank as stone.\nIt is already evening with a soft breeze\nSky torn between light and dark.\nLet the willow’s yellow flame tremble\nOn the dark horses robed\nFor my funeral.\nWhen the stars come\nLet them not fall upon my candle\nBut break into flame\nOn the willow branch\nSo it can  bloom.",
      },
    ],
  },
  {
    name: "Oleksa Slisarenko",
    slug: "oleksa-slisarenko",
    deathYear: "1937",
    deathMonth: "11",
    startYear: "1910",
    imageFile: "slisarenko.jpeg",
    years: "1891–1937",
    bio: `Slisarenko, Oleksa (Слісаренко, Олекса; pseud of Oleksa Snisar), b 28 March 1891 in Konivtsov khutir (now Shyputove), Vovchansk county, Kharkiv gubernia, d 3 November 1937 in Sandarmokh, Karelia region, RSFSR. Poet and prose writer. In the 1920s he moved to Kharkiv, where he became editor at the Knyhospilka publishing house. He was also coeditor of Universal’nyi zhurnal (1928–9). His first published poems appeared in 1910–11, in the student journal Do pratsi and in Rillia. In Kyiv he joined the Bila Studiia group of Ukrainian symbolists and met with members of the Muzahet group. His first anthology of symbolist poetry, Na berezi Kastal’s’komu (On the Kastal Coast, 1919), was marked by the influence of Pavlo Tychyna, Oleksander Oles, and Konstantin Balmont and other Russian symbolists. It also evinced some elements of expressionism. He subsequently joined the Panfuturist organizations Association of Panfuturists and Komunkult and published the collections of futurist poems Poemy (Poems, 1923) and Baida (1928). His attention to form and to poetic expression is evident.\n\nSlisarenko began writing prose in 1924 and published over 20 collections of English- and American-style crime-adventure stories, including Bunt (The Revolt, 1928), Zlamanyi gvynt (The Broken Bolt, 1929), Chornyi Anhel (Black Angel, 1929), Khlibna rika (The River of Bread, 1932), and Straik (Strike, 1932). His prose deals mainly with the period immediately preceding and during the Revolution of 1917, and his protagonists are antiheroes, people who are thrust into collisions with the revolution. Slisarenko also wrote poetry for children. In 1931 he published a collection of stories under the pseudonym Omelko Buts, Posmertna zbirka tvoriv (Posthumous Collection of Works). A selection of his works appeared in 1930, and a complete six-volume edition was published in 1931–3.\n\nSlisarenko was repressed during the Stalinist terror because of his ties to the symbolists and Panfuturists, his membership in Hart and Vaplite, and, particularly, his sharp rebuke of Maxim Gorky in 1927, after Gorky refused to permit the publication of a translation of Mat’ (Mother) into Ukrainian. He was arrested in 1934 and sent to the Solovets Islands, where he was shot. In the late 1950s he was ‘rehabilitated,’ and his novels Bunt and Chornyi Anhel were republished in 1965 and 1990. A more extensive edition of his selected prose and poetry, compiled by Vira Aheieva, was published by the Smoloskyp Publishers in Kyiv in 2011.`,
    poems: [],
    unavailable: "The poems have not been translated yet",
  },
  {
    name: "Mykola Zerov",
    slug: "mykola-zerov",
    deathYear: "1937",
    deathMonth: "11",
    startYear: "1912",
    imageFile: "zerov.jpg",
    years: "1890–1937",
    bio: "Zerov, Mykola, b 26 April 1890 in Zinkiv, Poltava gubernia, d 3 November 1937 in Sandarmoch, Karelia, RSFSR. Poet, translator, and literary historian; brother of Dmytro Zerov and Mykhailo Orest. He studied philology at Kyiv University. From 1917 to 1920 he edited the bibliographical journal Knyhar. He was a professor of Ukrainian literature at the Kyiv Architecture Institute (1918–20), the Kyiv Co-operative Tekhnikum (1923–5), and the Kyiv Institute of People's Education (1923–35). He also taught the theory of translation at the Ukrainian Institute of Linguistic Education (1930–3). He was arrested by the NKVD in April 1935 and sentenced to 10 years' imprisonment in the Solovets Islands. On 9 October 1937 he was resentenced, to death by firing squad and perished during the mass executions of political and other prisoners marking the twentieth anniversary of the October Revolution of 1917.\n\nZerov's literary activity, both as a poet and as a translator, was in complete harmony with his ideals and theoretical postulates. An avowed classicist and Parnassian, he became the leader of the Neoclassicists. He concentrated on the sonnet and Alexandrine verse and produced excellent examples of both forms. He translated numerous works of Latin poetry. He also devoted attention to sonnets in other literatures and translated the works of J.-M. de Heredia, P. de Ronsard, J. du Bellay, Adam Mickiewicz, Ivan Bunin, and others. He wrote literary criticism on contemporary Soviet Ukrainian literary works, articles on literary translation, and introductions to editions of Ukrainian classics; edited anthologies; and took part in the Literary Discussion. His published translations include Antolohiia ryms’koï poeziï (An Anthology of Roman Poetry, 1920), Kamena (1924; 2nd edn 1943), and Juliusz Słowacki's Mazepa (1925). Among his poetic works edited and published posthumously abroad by his brother Mykhailo Orest are Sonnetarium (1948), Catalepton (1952), and Corollarium (1958). His literary histories include Nove ukraïns’ke pys’menstvo (New Ukrainian Writings, vol 1, 1924), Do dzherel (To the Sources, 1926; 2nd edn 1943), Vid Kulisha do Vynnychenka (From Kulish to Vynnychenko, 1928), and Lektsiï z istoriï ukraïns’koï literatury (Lessons on the History of Ukrainian Literature, 1977). In 1958 Zerov was formally rehabilitated, and Vybrane (Selections) of his poetry was published in 1966, but a full rehabilitation was blocked by hostility from official critics, such as Leonid Novychenko and Mykola Shamota. In the late 1980s, on the initiative of Hryhorii Kochur, Zerov's works began to be collected seriously for publication. The fullest edition of his works was published in 1990 in two volumes. Zerov's collected works of literary criticism and scholarship appeared under the title Ukraïns’ke pys’menstvo (Ukrainian Literature) in 2003.",
    poems: [],
    unavailable: "The poems have not been translated yet",
  },
  {
    name: "Volodymyr Sosyura",
    slug: "volodymyr-sosyura",
    deathYear: "1965",
    deathMonth: "1",
    startYear: "1918",
    imageFile: "",
    years: "1898–1965",
    bio: "Sosiura, Volodymyr [Sosjura], b 6 January 1898 in Debaltseve, Katerynoslav gubernia, d 8 January 1965 in Kyiv. (Photo: Volodymyr Sosiura.) Poet. During the Ukrainian-Soviet War, 1917–21 he fought in the Army of the Ukrainian National Republic and then in the Red Army. After the war ended, he studied at the Artem Communist University in Kharkiv (1922–3) and at the workers' faculty of the Kharkiv Institute of People's Education (1923–5). He was a member of the literary organizations Pluh, Hart, Vaplite, and the All-Ukrainian Association of Proletarian Writers. His first poem to be published appeared in 1917. His first collection, Poeziï (Poems), published in 1921, was followed by his Romantic revolutionary poem Chervona zyma (The Red Winter, 1922), which was acclaimed as the best example of epic poetry from the period of the struggle for independence (1917–20) in Ukraine, and brought him fame overnight. Sosiura was to write many other works thematically based on that struggle, in which he united intimate, community, and universal concerns, such as in the collections Misto (The City, 1924), Snihy (The Snows, 1925), and Zoloti shuliky (The Golden Hawks, 1927).\n\nHis poems, filled with an organic lyricism, leave an impression of sincerity, revolutionary enthusiasm, and passionate feeling. Sosiura drew his unique lyrical style from the wellspring of folk literature. His style leaned toward classically simple verse, a songlike quality, and a Romantic, uplifted mood. Even in his early period Sosiura's poetry reflected his era and its contradictions, such as the impossibility of uniting loyalty to the Bolshevik revolution with feelings of duty toward one's country, a dilemma faced by all the Ukrainian intelligentsia of the 1920s. It can be seen in the poem about internal strife (between communard and nationalist) Dva Volod’ky (The Two Volodias, 1930) and in the collection Sertse (The Heart, 1931), which was banned immediately after its release.\n\nAlthough Sosiura had been a Party member since 1920, until the early 1930s his poetry brought him into conflict with the Communist party. That, together with the deaths of millions of Ukrainian peasants as a result of the Famine-Genocide of 1932–3 and the persecution and shootings of Ukrainian cultural activists during the 1930s, brought Sosiura near to a mental breakdown. Despite those difficult circumstances he was virtually the only poet in Ukraine in the 1930s who continued to work on lyric love poetry, such as in the collections Chervoni troiandy (Red Roses, 1932), Novi poeziï (New Poems, 1937), Liubliu (I Love, 1939), and Zhuravli pryletily (The Cranes Have Returned, 1940). From 1942 to 1944 Sosiura was a war correspondent. During that period he produced the collections Pid hul kryvavyi (During the Bloody Rumblings of War, 1942) and V hodynu hnivu (In the Hour of Anger, 1942) and the poem ‘Oleh Koshovyi’ (1943), among others. The most noteworthy of his postwar collections are Zelenyi svit (Green World, 1949), Solov'ïni dali (The Nightingale Distances, 1956), and Tak nikhto ne kokhav (No One Has Loved like This, 1960).\n\nAn important part of Sosiura's works are his poems written on a grander epic scale, such as the poems ‘1871’ (1923) and ‘Zaliznytsia’ (The Railway, 1924) and the versified novel Taras Triasylo (1926). In 1948 Sosiura was awarded the highest prize at that time, the Stalin Prize, but beginning in 1951 he was again harshly attacked. He was accused of bourgeois nationalism for his patriotic poem ‘Liubit' Ukraïnu’ (Love Ukraine), written in 1944. Although he was productive, Sosiura's poetic achievements were much less than his talents promised. His collected works have been published in 3 volume editions (1929–30 and 1957–8) and in 10 volumes (1970–2). In 1988 the poem ‘Mazepa,’ only excerpts of which had previously been published (1929), and the autobiographical novel Tretia rota (The Third Company) were published.",
    poems: [],
    unavailable: "The poems have not been translated yet",
  },
  {
    name: "Pavlo Fylypovych",
    slug: "pavlo-fylypovych",
    deathYear: "1937",
    deathMonth: "11",
    startYear: "1919",
    imageFile: "fylypovych.jpeg",
    years: "1891–1937",
    bio: "Fylypovych, Pavlo [Филипович, Павло; Fylypovyč], b 1 September 1891 in the village of Kaitanivka, Kyiv gubernia, d 3 November 1937 in Sandarmokh, Karelia, RSFSR. Poet and literary scholar. Fylypovych studied at Galagan College and at Kyiv University (1910–5), where he later was a professor (1917–35). His first poems were published, under the pseudonym Pavel Zorev, in Russian journals beginning in 1910. After the Revolution of 1917 Fylypovych switched to writing poetry in Ukrainian. He contributed to the Ukrainian symbolist almanac Muzahet (1919). In the 1920s he became a member of the Neoclassicists and published two collections of poetry—Zemlia i viter (Earth and Wind, 1922) and Prostir (Space, 1925). Fylypovych was an associate member of the All-Ukrainian Academy of Sciences and secretary of its Historical-Literary Society. His first major scholarly work was Zhizn’ i tvorchestvo E.A. Boratynskogo (The Life and Works of E.A. Boratynsky, 1917). Fylypovych is the author of over 100 scholarly articles and reviews. He made a major contribution to the comparative study of Ukrainian literature, particularly to the study of Taras Shevchenko and Ukrainian romanticism. He edited (and wrote introductions for) the collection of articles Shevchenko ta ioho doba (Shevchenko and His Period, 2 vols, 1925–6) and a collection on Ivan Franko (1927); he also edited, with long introductions, collections of works by Lesia Ukrainka, Olha Kobylianska, Oleksander Oles, Nikolai Gogol, Nikolai Leskov, and Aleksandr Pushkin. A collection of his literary studies, Z novitn’oho ukraïns’koho pys’menstva (From the New Ukrainian Literature), was published in 1929. Fylypovych was arrested in August 1935 during the Stalinist terror, presumably for his critical attitude to official Soviet cultural policies, and sentenced to 10 years in concentration camps. He was imprisoned in the Solovets Islands labor camp and murdered during the mass executions of political and other prisoners marking the twentieth anniversary of the October Revolution of 1917. His collected poems were published posthumously in Poeziï (Poems, Munich 1959), as were his major scholarly articles, collected in Pavlo Fylypovych, Literatura: Statti, rozvidky (Literature: Articles, Studies, Reviews, Melbourne 1971). In Ukraine, a book of Fylypovych’s poetry Poezii (Poems) appeared in Kyiv in 1989 and a collection of his literary studies was published in 1991.",
    poems: [],
    unavailable: "The poems have not been translated yet",
  },
  {
    name: "Marko Voronyi",
    slug: "marko-voronyi",
    deathYear: "1938",
    deathMonth: "6",
    startYear: "1932",
    imageFile: "",
    years: "1904–1937",
    bio: "Vorony, Marko [Вороний, Марко; Voronyj], b 5 March 1904 in Chernihiv, d 3 November 1937 in the Solovets Islands. (Photo: Marko Vorony.) Poet; son of Mykola Vorony. In the mid-1920s he published his poems in Literaturno-naukovyi vistnyk in Lviv, under the pseudonym Marko Antiokh. Under the same name he later published verse in Chervonyi shliakh, Zhyttia i revoliutsiia, Hlobus, and other journals. Collections of his poetry include Chervoni kravatky (Red Ties, 1930) and Forvard: Chotyry zoshyty virshiv (Forward: Four Notebooks of Poetry, 1932). He was arrested in March 1935 and was sentenced to eight years' imprisonment in the Solovets Islands. On 9 October 1937 he was resentenced by an NKVD tribunal to death by firing squad.",
    poems: [],
    unavailable: "The poems have not been translated yet",
  },
];

export const poetsUkr = [
  {
    name: "Максим Рильський",
    slug: "maxym-rylsky",
    deathYear: "1964",
    deathMonth: "07",
    startYear: "1907",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Євген Плужнюк",
    slug: "yevhen-pluzhnyuk",
    deathYear: "1936",
    deathMonth: "12",
    startYear: "1924",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Павло Тичина",
    slug: "pavlo-tychyna",
    years: "1891–1967",
    deathYear: "1967",
    deathMonth: "9",
    startYear: "1912",
    imageFile: "",
    bio: "",
    poems: [
      
    ],
  },
  {
    name: "Дмитро Загул",
    slug: "dmytro-zahul",
    deathYear: "1944",
    deathMonth: "6",
    startYear: "1909",
    imageFile: "zahul.jpeg",
    years: "",
    bio: "Zahul, Dmytro [Загул, Дмитро; pseuds: I. Maidan, B. Tyverets], b 28 August 1890 in Miliieve, Bukovyna, d 1944 in the Kolyma region. Writer. He belonged to the Muzahet group of symbolist poets. He later joined the Zakhidnia Ukraina group. His first published works appeared in the newspaper Bukovyna in 1907. Later he published in Hart, Hlobus, Zhyttia i revoliutsiia, Chervonyi shliakh, and other journals and almanacs. Collections of his poetry include Z zelenykh hir (From the Green Mountains, 1918), Na hrani (On the Edge, 1919), Nash den' (Our Day, 1923), Motyvy (Motifs, 1927), and the posthumous Vybrane (Selections, 1961). He also wrote a textbook on poetics, Poetyka (Poetics, 1923), a collection of essays in literary criticism, Literatura chy literaturshchyna? ( Literature or Literary Hackwork?, 1926), and a collection of translations, Vybir nimets'kykh baliad (A Selection of German Ballads, 1928). He was arrested on 26 February 1933 and sentenced to 10 years’ imprisonment in concentration camps. An edition of his poems was published in Kyiv in 1990.",
    poems: [],
  },
  {
    name: "Олекса Влизько",
    slug: "olexa-vlyzko",
    deathYear: "1934",
    deathMonth: "12",
    startYear: "1925",
    imageFile: "vlyzko.jpeg",
    years: "1908–1934",
    bio: "",
    poems: [],
  },
  {
    name: "Василь Мисик",
    slug: "vasyl-mysyk",
    deathYear: "1983",
    deathMonth: "3",
    startYear: "1923",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Микола Бажан",
    slug: "mykola-bazhan",
    deathYear: "1983",
    deathMonth: "11",
    startYear: "1923",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Михайло Драй-Хмара",
    slug: "mykhailo-drai-khmara",
    deathYear: "1939",
    deathMonth: "1",
    startYear: "1922",
    imageFile: "",
    years: "1889–1939",
    bio: `Mykhailo Drai-Khmara (1889-1939) was a Ukrainian poet, linguist, scholar and academic and one of the many major authors who died during the Soviet state's genocide of Ukraine in the 1930's. He was also a prolific translator, who recast Dante's "Inferno" into Ukrainian along with works by many other major European authors. However his sonnet Swans (1928), which celebrated Ukraine's five leading neoclassical poets, challenged the Soviet state's attempt to destroy Ukrainian culture. This beautiful poem initiated his fight against the authorities and was the beginning of the path that led to his death in a labour camp in Kolyma in 1939. It is believed that he laid down his life to save that of another prisoner.`,
    poems: [],
  },
  {
    name: "Богдан Ігор Антонич",
    slug: "bohdan-ihor-antonych",
    deathYear: "1937",
    deathMonth: "7",
    startYear: "1931",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Володимир Свідзинський",
    slug: "volodymyr-svidzinsky",
    deathYear: "1941",
    deathMonth: "10",
    startYear: "1912",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Олекса Слісаренко",
    slug: "oleksa-slisarenko",
    deathYear: "1937",
    deathMonth: "11",
    startYear: "1910",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Микола Зеров",
    slug: "mykola-zerov",
    deathYear: "1937",
    deathMonth: "11",
    startYear: "1912",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Володимир Сосюра",
    slug: "volodymyr-sosyura",
    deathYear: "1965",
    deathMonth: "1",
    startYear: "1918",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Павло Филипович",
    slug: "pavlo-fylypovych",
    deathYear: "1937",
    deathMonth: "11",
    startYear: "1919",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Марко Воронний",
    slug: "marko-voronyi",
    deathYear: "1938",
    deathMonth: "6",
    startYear: "1932",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
];
