export const poetsEng = [
  {
    name: "Maxym Rylsky",
    slug: "maxym-rylsky",
    deathYear: "1964",
    deathMonth: "7",
    startYear: "1907",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Yevhen Pluzhnyuk",
    slug: "yevhen-pluzhnyuk",
    deathYear: "1936",
    deathMonth: "12",
    startYear: "1924",
    imageFile: "pluzhnyk.jpeg",
    years: "1989–1936",
    bio: "Pluzhnyk, Yevhen [Плужник, Євген; Plužnyk, Jevhen], b 26 December 1898 in Kantemyrivka, Bohuchar county, Voronezh gubernia, d 31 January 1936 in the Solovets Islands. Writer. In the years 1923–8 he belonged to the Kyiv writers' groups Aspys, Lanka, and MARS and contributed poetry to several Soviet Ukrainian journals. During his lifetime he published only two poetry collections, Dni (Days) in 1926 and Rannia osin’ (Early Autumn) in 1927; a third, Rivnovaha (Equilibrium), first appeared posthumously in an émigré edition in Augsburg in 1948. He also wrote the novel Neduha (Illness, 1928), which was banned from circulation shortly after its publication. Two of his plays, Profesor Sukhorab and U dvori na peredmisti (In the Courtyard in the Suburb), appeared in Zhyttia i revoliutsiia in 1929; a drama in verse, ‘Shkidnyky’ (Wreckers), was never published. He also translated Russian literature into Ukrainian and compiled (with Valeriian Pidmohylny) a dictionary of Ukrainian official phraseology (1926) and (with Vasyl Atamaniuk and Feliks Yakubovsky) an anthology of Ukrainian poetry (1930–2).\nAlthough Pluzhnyk was one of the finest Ukrainian poets of the 1920s (he has been compared to Rainer Maria Rilke), Party criticism was hostile to his contemplative, laconic, and frequently gloomy lyricism and depiction of revolutionary atrocities and Soviet reality. After his novel was banned from circulation, he published very little. In December 1934 he was arrested together with many other Ukrainian figures, and in March 1935 he was sentenced by a military tribunal to death by firing squad. The verdict was commuted to 10 years' imprisonment in the Solovets Islands in the White Sea, where he soon died of the tuberculosis that had afflicted him since 1926. He was rehabilitated posthumously in 1956, and editions of his collected poems were published in Kyiv in 1966 and 1988. An uncensored edition appeared in Munich in 1979.",
    poems: [
      {
        title: "* * *",
        text: "I know that\nPloughshares are beaten out of swords. No soil becomes fertile because of\nThis art.\nSome keys there he that will afford Entrance into the entire heart. \n\nI perceive\nHow things are based:\nThrough all the wheat, blood is wove — Only thus people learn the taste\nOf love, \n\nI believe. \n",
      },
      {
        title: "* * *",
        text: "To learn wisdom — others don’t employ:\nAll mistakes must be your very own.\nWorks that have come down to us from Troy \nBorrowed were, for odes of ancient Rome.\n\nStudy well, even commas, by the way — \nAnd from each line a lesson you’ll partake: \nBetter make your own mistakes than, say, \nTry to learn from errors others make.",
      },
      {
        title: "* * *",
        text: "Night world in beauty wrought.\nNo symmetry. No utterance. Death inclined. \nSpeak not, then; speak not!\nWho or what throws words to the wind? \n\nAll the futility of a world beyond,\nAnd endless making of little worlds;\nHas not their meaning long been conned \nIn textbooks for the boys and girls! \nYet truly wrought in beauty — the night world! \n",
      },
      {
        title: "* * *",
        text: "Oh, when September-golden comes to pass \nAnd, like a laggard wandering,\nCaresses the silky fleece of autumn grass\nAnd cranes are gathered round a water-spring,\n\nAt night, I love to watch the deeper blue \nOf autumn's vaults of heaven draw\nThe raining stars, as carpenter would strew \nThe silvery shavings from his moving saw...\n\nWhat fiery light! For nature can afford\nFrom weariness to rest in beauty now released — \nWhich is perhaps in truth a high award\nFor summer's passion — grant of quiet peace.",
      },
      {
        title: "* * *",
        text: "Just a small town. But climb up the bell-tower — \nVista of rye fields and neighbouring farms,\nTown hall, houses, offices, drug-store —\nAll so familiar, all full of charm.\n\nI shall live quietly. \nLike when Fall is fair...\nAnd sit by my gate in the evenin’... \nOpposite lies the market square —\n\nThere play the dogs and the children.\nFolk don't need much, I know, to get by — \nJust a few memories, a room, some baccy — \nAnd sometimes a bit of blue sky.\nOr the Ninth symphony...",
      },
    ],
  },
  {
    name: "Pavlo Tychyna",
    slug: "pavlo-tychyna",
    years: "1891–1967",
    deathYear: "1967",
    bio: "Paulo Tychina (1891-1967) was born in the village of Pisky, Chernihiu Region, into the family of a deacon. One of the founders of new Soviet literature, he is the author of many books of verse, long poems, and poetry translations which won him nationwide recognition. His poetry is distinguished for its innovation, its wealth of themes, and profound insights into the inner world of Soviet man, the builder of communist society. His works have been translated into many Soviet and foreign languages. He also wrote a nurriber of scholarly works on Slavic, Oriental, and other literatures. Pavlo Tychina was a member of the Ukrainian SSR Academy of Sciences, corresponding member of the Academy of Sciences of Bulgaria, Hero of Socialist Labour, and a USSR State and Taras Shevchenko prize winner. The best literary works concerning the friendship of nations are annually awarded the Pavlo Tychina Prize.",
    poems: [
      {
        title: "HARPS RINGING, HARPS RINGING...",
        text: "Harps ringing, harps ringing —\ngolden ringing, loud resounding, through the \n            sing out your strings, \n         glad news echoing: \n      The fragrant spring’s \n      on the wing, \n   Flowering, dew-pearling, \n      painting every thing. \nThoughts flying, thoughts flying —\nlike a sea with white sails crowding, brim with \n               tender tones of blue, \n         flying thoughts that swirl: \n      Storms will come, \n      lightnings run! \n   Laughter be, weeping be \n   dews of mother-of-pearl... \nI arise, cast my eyes —\nrills all round like bells ajingle, larks pour down \n               in notes of gold \n            waterfalls that sing: \n      The fragrant spring’s \n      on the wing, \n   Flowering, dew-pearling, \n      painting every thing. \nLove of mine, heart of mine —\nshould you wander on the meadows all in sadness caught \n      or with joy awhirl: \n      Spare but one glance, 0 come! \n   Laughter be, weeping be \n      dews of mother-of-pearl. \n",
        year: "1914",
      },
    ],
    deathMonth: "9",
    startYear: "1912",
    imageFile: "",
  },
  {
    name: "Dmytro Zahul",
    slug: "dmytro-zahul",
    deathYear: "1944",
    deathMonth: "6",
    startYear: "1909",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Olexa Vlyzko",
    slug: "olexa-vlyzko",
    deathYear: "1934",
    deathMonth: "12",
    startYear: "1925",
    imageFile: "vlyzko.jpeg",
    years: "1908–1934",
    bio: "Vlyzko, Oleksa [Влизько, Олекса; Vlyz’ko], b 17 February 1908 in Korosten, Novgorod gubernia, Russia, d 14 December 1934 in Kyiv. Poet. He studied at the philological faculty of the Kyiv Institute of People's Education. He belonged to the literary organizations Molodniak and the All-Ukrainian Association of Proletarian Writers and later worked on the futurist journal Nova generatsiia. His first published poem was ‘Sertse na nord’ (Heart to the North) in the journal Hlobus (1925). Although Vlyzko paid the obligatory tribute to the Soviet way of life, his poetry was characterized by a search for new socialist forms of artistic expression, a cheerful romanticism, a love of the sea as a primal element, and interest in the adventures and passions of people of strong character. Vlyzko's poetry appeared in such collections as Za vsikh skazhu (I'll Speak on Everyone's Behalf, 1927), Poeziï (Poems, 1927), Zhyvu, pratsiuiu (I Live and I Work, 1930), Knyha baliad (The Book of Ballads, 1930), and P'iatyi korabel’ (Fifth Ship, 1933). In December 1934 he was arrested, accused of counterrevolutionary diversionary activities, and shot along with 28 other writers and cultural activists. During Nikita Khrushchev’s ‘thaw’ he was ‘rehabilitated.’ A posthumous collection was published in 1963, Vybrani poeziï (Selected Poems).",
    poems: [
      {
        title: "* * *",
        text: "Rich red blood, and my strength, open-handed \nLike Svyatogor, I would bring to the mass!.. \nAnd if hearts could but be expanded,\nI’d expand them a thousand times thus.\n\nAnd would scatter, would scatter, would scatter \nMy energy, like the bright sun’s rays,\nSo the world should catch fire, and batter\nAnd break down the bounds of ancient days!",
        year: "1927",
      },
      {
        title: "NINTH SYMPHONY",
        text: "Fire! Fire of superhuman love!\nIn youthful breasts let seethe the blood! \nI take you, oh my thorny world\nIn the sun’s embrace!\n            Like some warm bird \nMy fire-bird heart will fly around\nAll worlds. I’ll stretch o’er mankind’s bounds\n\nWide wings. Let fate be made beneath \nTheir shade. If men no heaven find,\nThey’ll find the hell-fire of young love, \nAll-human, strong, in which all wrong\nWill burn to ash — and that fierce heart \nBare-fanged, which drinks its brother’s gore \nWill fall, and never flourish more:\nThere’ll be no resurrecting it,\nJust as he’ll never rise, who falls \nInto those fierce and fiery jaws — \nThe human heart’s volcanic pit!..\n\nFire! Fire of superhuman storm!\nOf new love, wordless from the lips\nOf broken eunuchs, from the tongues\nOf hearts in gloves, that none, perhaps, \nShould see the skinny poisonous corpse \nWhere maggots breed —that noble dirt \nWhich rickety heirs have long preserved. \nDegenerates of the “true blue blood” \nWith blazoned arms of ancient homes. \nAnd suppuration ’neath golden cloaks!..\n\nFire! Fire of superhuman love!\nAlive for the strong, and dead for the dust. \nOf love impulsive and burning bright\nFor all things. Captivating might\nOf love for people, earth and beasts\nAs one. To live, to live like a sun!\nBy one’s own sweat true joy achieve\nFor one’s own sons, grandsons and heirs\nOf distant days!..\n         Fire! Fire of love!\nIn youthful breasts let seethe the blood!\n\nI take you, oh my thorny world\nIn the sun’s embrace! And in my love\nAs in fire, I place! Then burn with light\nAnd give to the poor blind wretch his sight, \nAnd blind the one, who the dark prefers, \nHimself inters in the graveyard mire!..\nMore sun, more light!! More love, more fire!!!",
        year: "1927",
      },
      {
        title: 'BALLAD OF "THE FLYING DUTCHMAN"',
        text: `The heavy\ncruiser\ngoes out\non her course.\nLike a rusty roof, \nthe land slowly goes. \nThe bridge. \nThe Captain.\nThe Devil’s own curse \non his evil lips,\nthe Zeiss\non his nose. \n\nIn his fury\nhe wrinkles\nhis frowning brow... \nAbove the horizon\nthe sun\nand blue haze;\nlike toad’s eyes\npeer the gun-barrels now, \ntheir steel beaks\nskyward\nthey raise.\nThere’s distant thunder. \nA choppy sea.\nThe warm foam\nchatters\nand spatters the deck. \nThe anchor rings.\nIn the foc’sle lee \nthe trap-ladder grates\nwith a quiet squeak... \n\nThe ocean lies dumb \nin the azure haze... \nA sudden\norder: \n“Change course! \nDue west!” \nAbove the horizon \na mast \nand cross-stays,\nwith a flag\nblood-red\n’gainst the blue impressed... \n\n\nAnd sharp\nas a jack-knife\nthat terse quick glance — \nand lieutenants\ndash up,\ntheir grins can't withhold, \nupon that ship,\non the tattered yards\nare strung up\ncorpses...\nB-r-r-r\nHow cold! \n\nStill nearer...\nStill nearer...\nThe horror grows... \nAnd the stench\nfloats over\nthe cruiser’s course... \nOn a light breeze \nsprung up\nit flows...\n“Reverse!\nAbout ship!”\nthe Captain roars.\nThe ship disappeared... \nA chill\nshook their bones...\nand as soon\nas night\non the foc’s’le\nfell,\na shivering sailor,\nin lowered tones\nof the “Flying Dutchman” \nbegan\nto tell...\nOn the waves\nthe wind\nhis bellows blew...\nAnd, bent o’er the bridge, \nand peering beneath,\nthe Captain listened.\nHis laughter flew\nlike a devil,\nin spasms,\nbetween his teeth: \n\n“The Flying Dutchman”?! \nHa-ha-ha! \nThey were Communards \nhung on that brig!\nhe cried.\nAnd suddenly, \nlosing his legs with a jar,\nin his twisted guts \nthe laughter \ndied,.. \n\nIn his fury\nhe wrinkles\nhis frowning brow... \nAbove the horizon\nthe gold,\nand blue haze;\nand like toad’s eyes\npeer the gun-barrels now, \ntheir steel beaks\nskyward\nthey gaping raise. \nThere’s distant thunder. \nA choppy sea.\nThe fine rain\nchatters\nand spatters the deck. \nThe anchor rings. \nIn the foc’s’le lee \nthe trap-ladder \nmockingly grates \nwith a squeak. \n\n\n`,
        year: "1930",
      },
    ],
  },
  {
    name: "Vasyl Mysyk",
    slug: "vasyl-mysyk",
    deathYear: "1983",
    deathMonth: "3",
    startYear: "1923",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Mykola Bazhan",
    slug: "mykola-bazhan",
    deathYear: "1983",
    deathMonth: "11",
    startYear: "1923",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Mykhailo Drai-Khmara",
    slug: "mykhailo-drai-khmara",
    deathYear: "1939",
    deathMonth: "1",
    startYear: "1922",
    imageFile: "khmara.jpg",
    years: "1889–1939",
    bio: `Mykhailo Drai-Khmara (1889-1939) was a Ukrainian poet, linguist, scholar and academic and one of the many major authors who died during the Soviet state's genocide of Ukraine in the 1930's. He was also a prolific translator, who recast Dante's "Inferno" into Ukrainian along with works by many other major European authors. However his sonnet Swans (1928), which celebrated Ukraine's five leading neoclassical poets, challenged the Soviet state's attempt to destroy Ukrainian culture. This beautiful poem initiated his fight against the authorities and was the beginning of the path that led to his death in a labour camp in Kolyma in 1939. It is believed that he laid down his life to save that of another prisoner.`,
    poems: [
      {
        title: "These Lips of Stone",
        text: "These lips of stone\n                      The tall rooftops\nGulping the curdled light\nLike Tatar Boza\nThe bee swarm clings to a vast honeycomb\n               Unmoving.\n               Its massive sleep.\nSwollen eyelids blink\nBeyond the city’s periphery\nFingers drum the guttering nervously.\nBoulevards\nSnow veined with dirt\n                                     Antique marble\nDarkening around tree stumps,\n                                    Wounds collapsing inwards\nThese tears that are not mine\nBut those of oaks fallen\nMy face and hands sprinkled with rain.\nWhy do you weep, blind ones\nLet the road\n                    Be covered with this dirty fabric\nLet it displace\n                      The pendent ice\n                      And believe\n              Soon soon\nThe rainbow will come\nSpring will chime\nIn the poorest dwelling,\n               Sunlight will festoon\n               Roses, though silently now\n               People in winter coats\n               Drift on sleighs through snow.",
      },
      {
        title: "Swans",
        text: "On the tranquil lake where willows dream\nLong tamed by both summer and Autumn\nThey splashdown,   flutter and swim \nTheir necks bend like heavily laden vines.\nWhen frosts come resonant as glass\nAnd waves whisper immersed in a white trance\nThese swimmers shatter the frozen space\nFearless, although winter threatens.\nOh cluster of five unconquered singers\nThrough snow and storm your song victorious\nBreaks the apathetic faithless ice.\nBe strong; from slavery and nothingness\nBe guided by the constellated Lyre\nTo worlds of light, oceans of foaming life.",
      },
    ],
  },
  {
    name: "Bohdan Ihor Antonych",
    slug: "bohdan-ihor-antonych",
    deathYear: "1937",
    deathMonth: "7",
    startYear: "1931",
    imageFile: "antonych.jpeg",
    years: "1909-1937",
    bio: "Antonych, Bohdan Ihor [Antonyč], b 5 October 1909 in Novytsia, Gorlice county in the Lemko region, d 6 July 1937 in Lviv. (Photo: Bohdan Ihor Antonych.) Poet, critic, and publicist. As a student in the arts and science faculty of Lviv University, Antonych assiduously studied the Ukrainian language and Ukrainian literature and wrote journalistic and critical articles under the pseudonym Zoil. He graduated in 1933. With V. Havryliuk and Volodymyr Lasovsky he co-edited the art journal Karby. Antonych edited the literary chronicle for the journal Dazhboh and for a time was its editor in chief. According to his own admission, Antonych was ‘a pagan in love with life,’ ‘a poet of spring intoxication.’ His lyrical poetry deals with a wide range of philosophical themes and combines the principles of imagism with a unique form of pantheism rooted in Lemko folklore. His religious attitude to folk objects and his extensive use of alliteration fascinated his contemporaries and have influenced later poets, notably Ihor Kalynets and Mykola Horbal.\n\nAntonych wrote the poetry collections: Pryvitannia zhyttia (Welcoming Life, 1931), Try persteni (Three Rings, 1934), and Knyha leva (The Book of the Lion, 1936). Zelena Ievanheliia (The Green Gospel, 1938), Rotatsiï (Rotations, 1938), and Vybrani poeziï (Selected Poems, ed Bohdan Romanenchuk, 1940) were published posthumously. In the 1960s there was renewed interest in Antonych's poetry. Various articles on and studies of his work appeared. Several annotated editions of his poetry were published: Persteni molodosti (The Rings of Youth, Bratislava 1966), Pisnia pro neznyshchennist' materiï (Song on the Indestructibility of Matter, Kyiv 1967), and Zibrani tvory (The Collected Works, ed Sviatoslav Hordynsky and Bohdan Rubchak, New York-Winnipeg 1967). The last collection includes, besides Antonych's poetry, his unfinished libretto Dovbush, fragments of the novel Na tomu berezi (On the Other Shore), his theoretical articles on art, journalistic articles, and book reviews. In the 1970s selections from his work were translated into Slovak (Očareny pohan [Košice 1976]) and into English (Square of Angels [New York 1977]). A bibliography of Antonych’s works, compiled by T. Kulchytska and N. Hraitser, appeared in 1989.",
    poems: [],
    unavailable: "The poems have not been translated yet",
  },
  {
    name: "Volodymyr Svidzinsky",
    slug: "volodymyr-svidzinsky",
    deathYear: "1941",
    deathMonth: "10",
    startYear: "1912",
    imageFile: "svidzynsky.jpg",
    years: "1885–1941",
    bio: "Svidzinsky, Volodymyr [Svidzins’kyj] (Svidzynsky), b 9 October 1885 in Maianiv, Vinnytsia county, Podilia gubernia, d 18 October 1941. (Photo: Volodymyr Svidzinsky.) Poet and translator. His first collection, Lirychni poeziï (Lyrical Poetry), was published in 1922; it was followed by Veresen’ (September 1927) and Poeziï (Poems, ed Yurii Yanovsky, 1940). His poems, written in 1927–36 and printed in Ukraine in the years 1937–40, were collected by Oleksa Veretenchenko and published in Munich in 1975 in the collection Medobir (Honey Wood). Poeziï (Poems, 1986) was a more recent edition of his work published in Ukraine. His collected poems and translations in two volumes were published in Kyiv in 2004. In his early collections Svidzynsky leaned toward symbolism, but in the two last collections there are elements of surrealism combined with classical forms. An important part of Svidzinsky's work is stories with folk or exotic motifs; there are also translations from the classics (Hesiod, Aesop, Ovid, Aristophanes) and from French, German, Polish, and Russian poetry. Svidzinsky died while under arrest, during the evacuation of Kharkiv in the fall of 1941. (According to eyewitness accounts, he was burned alive together with other prisoners in Saltiv, near Kharkiv. According to Soviet records, he was killed by a German bomb.)",
    poems: [
      {
        title: "The Lustre of Surfaces",
        text: "The lustre of surfaces dies into the shadow\nAnd antique silence sleeps,\nLike water decanted into a bowl.\nOnly my hands live,\nStrange and separate,\nTheir movements\nCompel me to meditate,\nLike the whisper of a leaf.\nI go to the window,\nA broken post stands by the verandah,\nMould grows in the guttering\nWhere snowflakes gather in winter,\nWhere birds alight in the morning.\nI press my forehead against the glass\nAnd gaze for a while.\nI don’t love the advent of night\nIt seems guilty, a dark linen,\nThe blurred green edges of vegetation.\nA huge pool of silence accumulates.\nWhere have the birds gone?\nThe lustrous surface of things dies,\nThe curtains hang motionless\nAs if carved in stone.\nIn my defined circle of silence\nI become more insensitive, and sad,\nAs a forgotten, Chinese lantern caught\nOn a branch in some old orchard.",
      },
      {
        title: `From "Treachery"`,
        text: "In the western fields at dusk\nThe ash doesn’t whisper\nThe jasmine is not fragrant\nAs at first light.\nHow  gently\nYou come over the horizon\nTo the violet in the glade.\nYou step towards her\nThe earth crackling\nWith autumn ice underfoot,\nAnd look beyond the path\nTo see grassy mounds\nSquat like bazaar stallholders\nSome solitary and others in pairs\nAnd the jasmine fades\nIn the yellow hands of buckthorn.\nCome\nWe will embrace you in auburn waters\nSwathe you in tangled grass\nGive you a maiden\nGreen of shoulder, smooth of belly\nLustrous eyed, the marsh’s beauty…”\nThe violet smiles\nAt how easily you are lured.\nThe silence is morose suddenly\nA maiden straight and tall\nYou stretch out your hand,\nShe is the night you call.\n",
      },
      {
        title: "Where wild chicory covered the street",
        text: "Where wild chicory covered the street\nIn a familiar circle\nWhere I would not place my feet\nThe doors were open\nBut only the night entered\nLimping clumsily\nAnd wearing no pale blue hat\nWith a zig-zag of grey silk.\nI embraced her before I spoke\n“Sweetheart how long I waited\nBy your window, when day came\nIt was not I troubling the branches\nOf mountain ash and cherry trees.”\nThe night leaves at dawn\nWith her friend the moon\nThey will sit together\nOn the shaking cart of sunlight\nWhen the orchids flutter\nAnd I’ll look from my verandah.\nDo not look at me or mock the night\nWith its deformed feet.\n",
      },
      {
        title: "I walk alongside the stream",
        text: "I walk alongside the stream\nA bird’s wings flash in the dusk\nDarkness thatches its shadow\nOn crag and alder.\nI walk alone…\nTense my forgotten hands\nWill I hear the fairy-tale whisper\nOf someone’s love.\nBut all around are familiar shapes,\nDarkness lisps mockingly\nThat I walk home\nThrough no fabled landscapes\nNo stories come. ",
      },
      {
        title: "It is already evening, a soft breeze",
        text: "It is already evening, a soft breeze\nBehind the leafless tree in the orchard\n(As if these two trees are not kindred)\nThe willow branches blossom\nWith a candle’s yellow flame\nLit for spring, its juvenile roar.\nWhy does it burn?\nIt is evening with a soft breeze,\nDo you see black horses to the east\nDressed as for some antique funeral\nEmerging from the dusk?\nThey will bear you back quietly\nAs the yellow flame is severed\nFrom the willow branch\nTo limp after them,\nIn dishevelled smoke will come\nTo the locked hollowness and bow\nWhere the north is blank as stone.\nIt is already evening with a soft breeze\nSky torn between light and dark.\nLet the willow’s yellow flame tremble\nOn the dark horses robed\nFor my funeral.\nWhen the stars come\nLet them not fall upon my candle\nBut break into flame\nOn the willow branch\nSo it can  bloom.",
      },
    ],
  },
  {
    name: "Oleksa Slisarenko",
    slug: "oleksa-slisarenko",
    deathYear: "1937",
    deathMonth: "11",
    startYear: "1910",
    imageFile: "slisarenko.jpeg",
    years: "1891–1937",
    bio: `Slisarenko, Oleksa (Слісаренко, Олекса; pseud of Oleksa Snisar), b 28 March 1891 in Konivtsov khutir (now Shyputove), Vovchansk county, Kharkiv gubernia, d 3 November 1937 in Sandarmokh, Karelia region, RSFSR. Poet and prose writer. In the 1920s he moved to Kharkiv, where he became editor at the Knyhospilka publishing house. He was also coeditor of Universal’nyi zhurnal (1928–9). His first published poems appeared in 1910–11, in the student journal Do pratsi and in Rillia. In Kyiv he joined the Bila Studiia group of Ukrainian symbolists and met with members of the Muzahet group. His first anthology of symbolist poetry, Na berezi Kastal’s’komu (On the Kastal Coast, 1919), was marked by the influence of Pavlo Tychyna, Oleksander Oles, and Konstantin Balmont and other Russian symbolists. It also evinced some elements of expressionism. He subsequently joined the Panfuturist organizations Association of Panfuturists and Komunkult and published the collections of futurist poems Poemy (Poems, 1923) and Baida (1928). His attention to form and to poetic expression is evident.\n\nSlisarenko began writing prose in 1924 and published over 20 collections of English- and American-style crime-adventure stories, including Bunt (The Revolt, 1928), Zlamanyi gvynt (The Broken Bolt, 1929), Chornyi Anhel (Black Angel, 1929), Khlibna rika (The River of Bread, 1932), and Straik (Strike, 1932). His prose deals mainly with the period immediately preceding and during the Revolution of 1917, and his protagonists are antiheroes, people who are thrust into collisions with the revolution. Slisarenko also wrote poetry for children. In 1931 he published a collection of stories under the pseudonym Omelko Buts, Posmertna zbirka tvoriv (Posthumous Collection of Works). A selection of his works appeared in 1930, and a complete six-volume edition was published in 1931–3.\n\nSlisarenko was repressed during the Stalinist terror because of his ties to the symbolists and Panfuturists, his membership in Hart and Vaplite, and, particularly, his sharp rebuke of Maxim Gorky in 1927, after Gorky refused to permit the publication of a translation of Mat’ (Mother) into Ukrainian. He was arrested in 1934 and sent to the Solovets Islands, where he was shot. In the late 1950s he was ‘rehabilitated,’ and his novels Bunt and Chornyi Anhel were republished in 1965 and 1990. A more extensive edition of his selected prose and poetry, compiled by Vira Aheieva, was published by the Smoloskyp Publishers in Kyiv in 2011.`,
    poems: [],
    unavailable: "The poems have not been translated yet",
  },
  {
    name: "Mykola Zerov",
    slug: "mykola-zerov",
    deathYear: "1937",
    deathMonth: "11",
    startYear: "1912",
    imageFile: "zerov.jpg",
    years: "1890–1937",
    bio: "Zerov, Mykola, b 26 April 1890 in Zinkiv, Poltava gubernia, d 3 November 1937 in Sandarmoch, Karelia, RSFSR. Poet, translator, and literary historian; brother of Dmytro Zerov and Mykhailo Orest. He studied philology at Kyiv University. From 1917 to 1920 he edited the bibliographical journal Knyhar. He was a professor of Ukrainian literature at the Kyiv Architecture Institute (1918–20), the Kyiv Co-operative Tekhnikum (1923–5), and the Kyiv Institute of People's Education (1923–35). He also taught the theory of translation at the Ukrainian Institute of Linguistic Education (1930–3). He was arrested by the NKVD in April 1935 and sentenced to 10 years' imprisonment in the Solovets Islands. On 9 October 1937 he was resentenced, to death by firing squad and perished during the mass executions of political and other prisoners marking the twentieth anniversary of the October Revolution of 1917.\n\nZerov's literary activity, both as a poet and as a translator, was in complete harmony with his ideals and theoretical postulates. An avowed classicist and Parnassian, he became the leader of the Neoclassicists. He concentrated on the sonnet and Alexandrine verse and produced excellent examples of both forms. He translated numerous works of Latin poetry. He also devoted attention to sonnets in other literatures and translated the works of J.-M. de Heredia, P. de Ronsard, J. du Bellay, Adam Mickiewicz, Ivan Bunin, and others. He wrote literary criticism on contemporary Soviet Ukrainian literary works, articles on literary translation, and introductions to editions of Ukrainian classics; edited anthologies; and took part in the Literary Discussion. His published translations include Antolohiia ryms’koï poeziï (An Anthology of Roman Poetry, 1920), Kamena (1924; 2nd edn 1943), and Juliusz Słowacki's Mazepa (1925). Among his poetic works edited and published posthumously abroad by his brother Mykhailo Orest are Sonnetarium (1948), Catalepton (1952), and Corollarium (1958). His literary histories include Nove ukraïns’ke pys’menstvo (New Ukrainian Writings, vol 1, 1924), Do dzherel (To the Sources, 1926; 2nd edn 1943), Vid Kulisha do Vynnychenka (From Kulish to Vynnychenko, 1928), and Lektsiï z istoriï ukraïns’koï literatury (Lessons on the History of Ukrainian Literature, 1977). In 1958 Zerov was formally rehabilitated, and Vybrane (Selections) of his poetry was published in 1966, but a full rehabilitation was blocked by hostility from official critics, such as Leonid Novychenko and Mykola Shamota. In the late 1980s, on the initiative of Hryhorii Kochur, Zerov's works began to be collected seriously for publication. The fullest edition of his works was published in 1990 in two volumes. Zerov's collected works of literary criticism and scholarship appeared under the title Ukraïns’ke pys’menstvo (Ukrainian Literature) in 2003.",
    poems: [],
    unavailable: "The poems have not been translated yet",
  },
  {
    name: "Volodymyr Sosyura",
    slug: "volodymyr-sosyura",
    deathYear: "1965",
    deathMonth: "1",
    startYear: "1918",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Pavlo Fylypovych",
    slug: "pavlo-fylypovych",
    deathYear: "1937",
    deathMonth: "11",
    startYear: "1919",
    imageFile: "fylypovych.jpeg",
    years: "1891–1937",
    bio: "Fylypovych, Pavlo [Филипович, Павло; Fylypovyč], b 1 September 1891 in the village of Kaitanivka, Kyiv gubernia, d 3 November 1937 in Sandarmokh, Karelia, RSFSR. Poet and literary scholar. Fylypovych studied at Galagan College and at Kyiv University (1910–5), where he later was a professor (1917–35). His first poems were published, under the pseudonym Pavel Zorev, in Russian journals beginning in 1910. After the Revolution of 1917 Fylypovych switched to writing poetry in Ukrainian. He contributed to the Ukrainian symbolist almanac Muzahet (1919). In the 1920s he became a member of the Neoclassicists and published two collections of poetry—Zemlia i viter (Earth and Wind, 1922) and Prostir (Space, 1925). Fylypovych was an associate member of the All-Ukrainian Academy of Sciences and secretary of its Historical-Literary Society. His first major scholarly work was Zhizn’ i tvorchestvo E.A. Boratynskogo (The Life and Works of E.A. Boratynsky, 1917). Fylypovych is the author of over 100 scholarly articles and reviews. He made a major contribution to the comparative study of Ukrainian literature, particularly to the study of Taras Shevchenko and Ukrainian romanticism. He edited (and wrote introductions for) the collection of articles Shevchenko ta ioho doba (Shevchenko and His Period, 2 vols, 1925–6) and a collection on Ivan Franko (1927); he also edited, with long introductions, collections of works by Lesia Ukrainka, Olha Kobylianska, Oleksander Oles, Nikolai Gogol, Nikolai Leskov, and Aleksandr Pushkin. A collection of his literary studies, Z novitn’oho ukraïns’koho pys’menstva (From the New Ukrainian Literature), was published in 1929. Fylypovych was arrested in August 1935 during the Stalinist terror, presumably for his critical attitude to official Soviet cultural policies, and sentenced to 10 years in concentration camps. He was imprisoned in the Solovets Islands labor camp and murdered during the mass executions of political and other prisoners marking the twentieth anniversary of the October Revolution of 1917. His collected poems were published posthumously in Poeziï (Poems, Munich 1959), as were his major scholarly articles, collected in Pavlo Fylypovych, Literatura: Statti, rozvidky (Literature: Articles, Studies, Reviews, Melbourne 1971). In Ukraine, a book of Fylypovych’s poetry Poezii (Poems) appeared in Kyiv in 1989 and a collection of his literary studies was published in 1991.",
    poems: [],
    unavailable: "The poems have not been translated yet",
  },
  {
    name: "Marko Voronnyi",
    slug: "marko-voronnyi",
    deathYear: "1938",
    deathMonth: "6",
    startYear: "1932",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
];

export const poetsUkr = [
  {
    name: "Максим Рильський",
    slug: "maxym-rylsky",
    deathYear: "1964",
    deathMonth: "07",
    startYear: "1907",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Євген Плужнюк",
    slug: "yevhen-pluzhnyuk",
    deathYear: "1936",
    deathMonth: "12",
    startYear: "1924",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Павло Тичина",
    slug: "pavlo-tychyna",
    years: "1891–1967",
    deathYear: "1967",
    deathMonth: "9",
    startYear: "1912",
    imageFile: "",
    bio: "",
    poems: [],
  },
  {
    name: "Дмитро Загул",
    slug: "dmytro-zahul",
    deathYear: "1944",
    deathMonth: "6",
    startYear: "1909",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Олекса Влизько",
    slug: "olexa-vlyzko",
    deathYear: "1934",
    deathMonth: "12",
    startYear: "1925",
    imageFile: "vlyzko.jpeg",
    years: "1908–1934",
    bio: "",
    poems: [],
  },
  {
    name: "Василь Мисик",
    slug: "vasyl-mysyk",
    deathYear: "1983",
    deathMonth: "3",
    startYear: "1923",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Микола Бажан",
    slug: "mykola-bazhan",
    deathYear: "1983",
    deathMonth: "11",
    startYear: "1923",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Михайло Драй-Хмара",
    slug: "mykhailo-drai-khmara",
    deathYear: "1939",
    deathMonth: "1",
    startYear: "1922",
    imageFile: "",
    years: "1889–1939",
    bio: `Mykhailo Drai-Khmara (1889-1939) was a Ukrainian poet, linguist, scholar and academic and one of the many major authors who died during the Soviet state's genocide of Ukraine in the 1930's. He was also a prolific translator, who recast Dante's "Inferno" into Ukrainian along with works by many other major European authors. However his sonnet Swans (1928), which celebrated Ukraine's five leading neoclassical poets, challenged the Soviet state's attempt to destroy Ukrainian culture. This beautiful poem initiated his fight against the authorities and was the beginning of the path that led to his death in a labour camp in Kolyma in 1939. It is believed that he laid down his life to save that of another prisoner.`,
    poems: [],
  },
  {
    name: "Богдан Ігор Антонич",
    slug: "bohdan-ihor-antonych",
    deathYear: "1937",
    deathMonth: "7",
    startYear: "1931",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Володимир Свідзинський",
    slug: "volodymyr-svidzinsky",
    deathYear: "1941",
    deathMonth: "10",
    startYear: "1912",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Олекса Слісаренко",
    slug: "oleksa-slisarenko",
    deathYear: "1937",
    deathMonth: "11",
    startYear: "1910",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Микола Зеров",
    slug: "mykola-zerov",
    deathYear: "1937",
    deathMonth: "11",
    startYear: "1912",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Володимир Сосюра",
    slug: "volodymyr-sosyura",
    deathYear: "1965",
    deathMonth: "1",
    startYear: "1918",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Павло Филипович",
    slug: "pavlo-fylypovych",
    deathYear: "1937",
    deathMonth: "11",
    startYear: "1919",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
  {
    name: "Марко Воронний",
    slug: "marko-voronnyi",
    deathYear: "1938",
    deathMonth: "6",
    startYear: "1932",
    imageFile: "",
    years: "",
    bio: "",
    poems: [],
  },
];
